### ISSUE TITLE
Privacy enhancement - Toggling Google password manager off

### ISSUE THREAD

**Issue by edo0** [kiwibrowser/src#100]
I think it would be great for many of us more privacy-conscious users to have the option not to sync saved passwords with one's google account.

Would there be the chance to allow opting out of the feature - possibly adding a toggle to the relevant setting?
Thank you in advance!

**Comment by d3ward** [comment]
Check out latest Kiwi builds  on [src.next](https://github.com/kiwibrowser/src.next)
