### ISSUE TITLE
Feature request: OpenSearch 

### ISSUE THREAD

**Issue by TheEvilSkeleton** [kiwibrowser/src#101]
Hello, so there is a feature by the name of [OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch), which is explained by the [Bromite team](https://github.com/bromite/bromite/wiki/SearchEngines#set-your-default-search-engine). I tried to set a custom search engine, but it didn't work, and I am assuming that is because Kiwi does not support OpenSearch. The image should look like this after visiting some websites (taken from Bromite, under `Recently visited`):

![image](https://user-images.githubusercontent.com/50847364/82917672-b49b7900-9f41-11ea-9691-6057d10fbd9b.png)

[Bromite is open source](https://github.com/bromite/bromite), so you can look at their source code and see what you can do with it.

**Comment by Madis0** [comment]
This is from Chromium itself, if it doesn't work in Kiwi it must be because of a change in Kiwi itself.

**Comment by hjyoung1** [comment]
![Screenshot_20200531-004704543](https://user-images.githubusercontent.com/45882061/83337389-823ea280-a2d8-11ea-918b-be770a751221.jpg)
Using kiwi browser. After searching on apk mirror it's available as search engine in settings.

**Comment by TheEvilSkeleton** [comment]
You're right, it's working for me too, thank you for the correction
