### ISSUE TITLE
tap word and google search not working (no result appear neither below nor in new tab) 

### ISSUE THREAD

**Issue by buvanbamm** [kiwibrowser/src#107]
![Screenshot_20200530111346](https://user-images.githubusercontent.com/59174543/83334042-65e33b80-a2c1-11ea-83b5-cf1ca6d44951.jpg)

**Comment by hjyoung1** [comment]
![Screenshot_20200531-001716792 (1)](https://user-images.githubusercontent.com/45882061/83336822-338f0980-a2d4-11ea-8d58-b62328222a4a.jpg)
Works fine for me. Are you using latest version of kiwibrowser? Play store or dev builds?

**Comment by buvanbamm** [comment]
github

**Comment by d3ward** [comment]
Check out latest Kiwi builds  on [src.next](https://github.com/kiwibrowser/src.next)
