### ISSUE TITLE
simplified view and translator doesn't interact to each other 😂

### ISSUE THREAD

**Issue by buvanbamm** [kiwibrowser/src#108]
![Screenshot_20200529173853](https://user-images.githubusercontent.com/59174543/83334210-819b1180-a2c2-11ea-9e8f-f8f8915c0fde.jpg)

![Screenshot_20200529174231](https://user-images.githubusercontent.com/59174543/83334215-88298900-a2c2-11ea-9d70-d4a27bd0af56.jpg)

issue is 
simplified blog lack translator option and translated blog failed to load in simplified view

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
