### ISSUE TITLE
Add ability to block cookies for a domain

### ISSUE THREAD

**Issue by cglong** [kiwibrowser/src#110]
Chrome has the ability to block all cookies for a specific domain. Can this be added to Kiwi as well?
![Screenshot_20200603-220024](https://user-images.githubusercontent.com/137214/83706638-00a38900-a5e6-11ea-9b12-0dde93f6fc7c.png)

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
