### ISSUE TITLE
Please add widevine drm support

### ISSUE THREAD

**Issue by philS1** [kiwibrowser/src#111]
This webpage shows no drm support in kiwi browser:https://bitmovin.com/demos/drm

On ungoogled-chromium this is already implemented. I think it's a library using the PPAPI

**Comment by kiwibrowser** [comment]
I wrote to Google about that today. I got a reply they are still "investigating" if it's possible (of course it is).

I will push them again in about a week.

**Comment by philS1** [comment]
Thans for investigation. Is it needed to contact googled? Ungoogled-chromium for android already has this feature implemented. Or is it a license issue?

**Comment by kiwibrowser** [comment]
Absolutely licensing issue, to integrate Widevine proprietary components you need approval and license (from a both paper and technical perspective).

I saw the workaround you have shown at ungoogled-chromium, it may work, and may be a last resort solution (but not-bundled officially within Kiwi).

**Comment by philS1** [comment]
Any response by google so far?

**Comment by philS1** [comment]
Push

**Comment by philS1** [comment]
Push

**Comment by kiwibrowser** [comment]
Google answered today and resolved the issue apparently. The last version should have functional Widevine (you need to accept protected content permission prompt)

**Comment by kiwibrowser** [comment]
Google answered today. The last version should have functional Widevine (you need to accept protected content permission prompt)
