### ISSUE TITLE
Nextcloud Passwords: Your Browser is outdated

### ISSUE THREAD

**Issue by nesasio93** [kiwibrowser/src#113]
I can't access my passwords with Kiwi on my phone. Nextcloud Passwords says my browser is outdated. I tried setting a custom useragent till whatismybrowser.com said my browser is up-to-date, but passwords is still marking Kiwi as outdated. 

Not being able to access my passwords sadly keeps me using firefox.

I followed #94 and it seems it needs time till kiwi has an updated chromium version, so what can I do to make passwords work?

PS: Nice work with Kiwi! With this bug out of my way it would become my main browser! :)

**Comment by bitsper2nd** [comment]
This is a not really a Kiwi-browser problem. I suggest you use a [NextCloud client](https://github.com/daper/nextcloud-passwords-app) and close this issue.

**Comment by nesasio93** [comment]
Of course it's a Kiwi problem. There is simply something Kiwi can not do and other browsers can.

> Really, if you see a bug (of any nature, security, not security) if you see it fixed in Chromium and want Kiwi to include it, you can show it here and as soon as the lines of code are imported you'll get an APK automatically with the fixes.

According to @kiwibrowser in #94 

And that is all I did: pointing out a bug

**Comment by rururux** [comment]
yeah it's not because the kiwi's useragent is old, but because kiwi doesn't support "WebAssembly.instantiate".
unfortunately, you'll have to use it in another browser until the kiwi's engine is updated.

![outdated](https://user-images.githubusercontent.com/5568054/84120628-0f1ff380-aa71-11ea-8075-e1a6a7680eb1.png)
![Screenshot_20200609-170437](https://user-images.githubusercontent.com/5568054/84122510-7fc80f80-aa73-11ea-857d-2d7c8469ace2.png)

**Comment by hjyoung1** [comment]
If it's because of lack of webassembly support( https://github.com/kiwibrowser/src/issues/113#issuecomment-641111214) then you can enable this flag as a workaround. @nesasio93 
chrome://flags/#enable-webassembly-streaming

**Comment by rururux** [comment]
Wow! this seems promising.
after enabled #enable-webassembly-streaming

![Screenshot_20200609-180135~01](https://user-images.githubusercontent.com/5568054/84128589-bbff6e00-aa7b-11ea-8ee4-0002823dc28c.png)

**Comment by nesasio93** [comment]
Great! With #enable-webassembly-streaming enabled I can access my passwords by directly open my nextcloud page. Thank you @hjyoung1 !

The last step would be to get the extension working. The extension simply does not show any passwords and according to the nextcloud security overview it does not access the passwords at all. The access seems to be blocked beforehand.

https://chrome.google.com/webstore/detail/nextcloud-passwords/mhajlicjhgoofheldnmollgbgjheenbi
https://github.com/marius-wieschollek/passwords-webextension

With the extension working in Kiwi a few month ago I still believe this is a Kiwi bug

**Comment by pythonInRelay** [comment]
@bitsper2nd it's happening now across many websites, it is definitely a Kiwi issue as it does not happen with other clients.

**Comment by bitsper2nd** [comment]
> 
> 
> @bitsper2nd it's happening now across many websites, it is definitely a Kiwi issue as it does not happen with other clients.

I will give the benefit of the doubt. please share with the dev in here a list of sites not supported in kiwi.

**Comment by d3ward** [comment]
#78
