### ISSUE TITLE
Some sites now reporting "Out of date browser"

### ISSUE THREAD

**Issue by pythonInRelay** [kiwibrowser/src#116]
Loads of sites, especially those using HTML5 video are now reporting an "Out of Date Browser" page and requesting I download another 'more modern' Android browser. Could we get the Chromium base updated please?

Also seems to be related to #113

**Comment by blubbll** [comment]
fake your user agent ᕕ( ᐛ )ᕗ

**Comment by pythonInRelay** [comment]
> 
> 
> fake your user agent ᕕ( ᐛ )ᕗ

I've actually tried this, is does not work.

**Comment by hjyoung1** [comment]
Tried enabling webassembly flag?

**Comment by pythonInRelay** [comment]
Thank you for your reply.

> 
> 
> If it's because the lack of webassembly support( [#113 (comment)](https://github.com/kiwibrowser/src/issues/113#issuecomment-641111214)) then you can enable this flag as a workaround for now. @nesasio93
> chrome://flags/#enable-webassembly-streaming

This did not work either sadly. Exact same message _"Dear user, your browser is too old! <site> supports only modern, secure browsers! Please update your browser or choose another browser to continue"_

Navigating to any other URL redirects to the same message. It's a forced page redirect so not a popup or otherwise that I can block either. I think the base just needs to be updated. Regular Chrome for Android works fine.

**Comment by robsmith11** [comment]
Why not share the URL for others to test?  Are you embarrassed that it's porn or something?

**Comment by nesasio93** [comment]
I described my personal problem in #113, which is a dealbreaker for me. No other problems atm.

**Comment by d3ward** [comment]
#78
