### ISSUE TITLE
Ultra White Theme colors?

### ISSUE THREAD

**Issue by csehszlovakze** [kiwibrowser/src#118]
I'd like to see the following parts of the browser also turned light:
1. background of the tab bar
2. the "no tabs" page (right now it's dark gray with black buttons)

Screenshots of current state:
1.
![Screenshot_20200616-130817_Kiwi Browser (1)](https://user-images.githubusercontent.com/50457795/84769040-84da1100-afd5-11ea-8a65-2d51ebe95ae6.jpg)
2.
![Screenshot_20200616-130828_Kiwi Browser (1)](https://user-images.githubusercontent.com/50457795/84769042-860b3e00-afd5-11ea-9530-a56a91240dd9.jpg)

Desired look (made in GIMP):
1.
![Screenshot_20200616-130817_Kiwi Browser (2)](https://user-images.githubusercontent.com/50457795/84769081-96231d80-afd5-11ea-80f8-385f8a4d270a.jpg)
2.
![Screenshot_20200616-130828_Kiwi Browser (2)](https://user-images.githubusercontent.com/50457795/84769083-96bbb400-afd5-11ea-8e41-326ad3105c3d.jpg)

(p.s. I removed my speed dial icons for privacy.)

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
