### ISSUE TITLE
Browser unusable with Samsung Dex

### ISSUE THREAD

**Issue by NekoGryphou** [kiwibrowser/src#120]
When I use my Samsung Dex, the kiwi interface changes to look like Chrome PC, the browser becomes completely unusable...  
Website are croped, tab not working at all...
Attached is a video explaining the problem

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/40165444/85378722-38de1d80-b53b-11ea-8bd5-c6b48625215e.gif)

**Comment by NekoGryphou** [comment]
No care about my ticket ?

**Comment by kiwibrowser** [comment]
When you try by disabling the bottom bar do you have the same issue ?
It seems like you got between two modes (tablet where bottom bar is not available, and bottom address bar on)

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
