### ISSUE TITLE
Copy / Paste problem

### ISSUE THREAD

**Issue by NekoGryphou** [kiwibrowser/src#121]
When copying and pasting, if the browser is open, it does not take into account the last copy made from another application. 
Attached is an explanatory video
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40165444/85378478-e7ce2980-b53a-11ea-87cd-dcde58678914.gif)

**Comment by hjyoung1** [comment]
Duplicate of #26

**Comment by borealis999** [comment]
This is already a well-known issue in the Kiwi community. This additional issue is unnecessary.

**Comment by kiwibrowser** [comment]
Testing a fix @ https://github.com/kiwibrowser/src/commit/8419f2f07faf34d416ca50d7f924413dd0eb2eac
