### ISSUE TITLE
Add option to display tabs as grid

### ISSUE THREAD

**Issue by NekoGryphou** [kiwibrowser/src#122]
Could you add an option to allow **tabs** to be displayed as a **grid** rather than a scrolling menu?

Example of grid **tabs** :
![chrome-android-tab-grid](https://user-images.githubusercontent.com/40165444/85417337-c63b6500-b56f-11ea-96fc-1f388650f2d6.png)

**Comment by hjyoung1** [comment]
https://github.com/kiwibrowser/src/issues/94#issuecomment-634069630

**Comment by d3ward** [comment]
Added ! Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
