### ISSUE TITLE
Text of different size, overlaid and thus poorly readable

### ISSUE THREAD

**Issue by M-A-R-T-I-N-1** [kiwibrowser/src#123]
[http://fyzika.jreichl.com/main.article/view/5-trajektorie-a-draha-hmotneho-bodu](http://fyzika.jreichl.com/main.article/view/5-trajektorie-a-draha-hmotneho-bodu) 

The `<div>` seems to be expanded by line wrapping but the headline doesn't seem to be shifted down accordingly. Furthermore, in Chrome the size of the text where line wrapping occurs is much smaller. 

Kiwi:
![Screenshot_20200629-134707](https://user-images.githubusercontent.com/43148954/86001538-4d288b80-ba0f-11ea-8421-e2c2125a5613.png)

Chrome:
![Screenshot_20200629-134649](https://user-images.githubusercontent.com/43148954/86001545-5154a900-ba0f-11ea-851b-7b1fcbb72898.png)

**Comment by d3ward** [comment]
This has been fixed .
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
