### ISSUE TITLE
Night mode doesn't fully work on searchbar on the very right

### ISSUE THREAD

**Issue by M-A-R-T-I-N-1** [kiwibrowser/src#126]
[https://git.busybox.net/busybox](https://git.busybox.net/busybox) 

The search bar on the right does have white text, that's correct, but the background is also white, which is a problem. 

(Have highest contrast set.)

**Comment by d3ward** [comment]
This has been fixed. 
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
