### ISSUE TITLE
Audio Latency/Lag on Duolingo

### ISSUE THREAD

**Issue by phly95** [kiwibrowser/src#127]
With Duolingo, when you tap a bubble that produces audio, there is a delay. There delay gets really bad when connecting a Bluetooth device (though it can be reduced by connecting the Bluetooth device while playing audio on the internal speakers). This seems to be a Chromium bug, since Google Chrome seems to have this issue too.

Both Firefox Standard as well as Preview/Beta do not suffer these latency issues.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
