### ISSUE TITLE
Switching night mode or reloading won't preserve the viewed location on the site

### ISSUE THREAD

**Issue by M-A-R-T-I-N-1** [kiwibrowser/src#128]
[https://en.m.wikipedia.org/wiki/Elasticity_(physics)](https://en.m.wikipedia.org/wiki/Elasticity_(physics)) 

When you switch the night mode off to see formulas or if you reload the page, you end up viewing the very first section of the site. 

I might be useful to scroll to the last position after the sections expand. (It might help to check for page size change after loading and if the size matches to the size before reload, scroll to the saved position. Or do so even if the size doesn't match, not sure if that's a good idea to do it when the sizes don't match, though.)

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
