### ISSUE TITLE
Night mode doesn't fully work for combo boxes

### ISSUE THREAD

**Issue by M-A-R-T-I-N-1** [kiwibrowser/src#130]
[http://corelangs.com/js/progs/options.html](http://corelangs.com/js/progs/options.html) 

The text in combo boxes is white, that's correct, but the box itself is also white, which is a problem.

**Comment by d3ward** [comment]
That bug is fixed . Check out latest Kiwi builds  on [src.next](https://github.com/kiwibrowser/src.next)
