### ISSUE TITLE
Night mode doesn't fully work for login controls

### ISSUE THREAD

**Issue by M-A-R-T-I-N-1** [kiwibrowser/src#131]
[https://idp.upce.cz/jasig/login](https://idp.upce.cz/jasig/login) 

When the night mode is activated, typing credentials results in white text on white background: 
![Screenshot_20200706-083817](https://user-images.githubusercontent.com/43148954/86563571-e5b99100-bf64-11ea-8349-f71bbc74d603.png)

The night mode doesn't work at all for the suggestion box. 
However selecting a suggestion results in application of correct formatting to the respective field: 

![Screenshot_20200706-084300](https://user-images.githubusercontent.com/43148954/86563516-cde20d00-bf64-11ea-8c06-4584944f628c.png)

**Comment by M-A-R-T-I-N-1** [comment]
Fixing this might fix #126 as well.

**Comment by d3ward** [comment]
Check out latest Kiwi builds, since these bugs has been fixed
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
