### ISSUE TITLE
Switching the night mode on different tab doesn't handle tab switching correctly

### ISSUE THREAD

**Issue by M-A-R-T-I-N-1** [kiwibrowser/src#132]
[https://github.com/kiwibrowser/src/issues/new](https://github.com/kiwibrowser/src/issues/new)

Activation of night mode when viewing the tab with the site above and "Test" in the title field works correctly (except #125). However when the night mode is activated on different tab, the site will look like this:
![Screenshot_20200706-095228](https://user-images.githubusercontent.com/43148954/86569396-a09a5c80-bf6e-11ea-89ba-75fcaa3b5db3.png)

Other way around:
![Screenshot_20200706-095827](https://user-images.githubusercontent.com/43148954/86569798-45b53500-bf6f-11ea-90bd-fa70f28f3e9a.png)

The new issue site with "Test" in the issue text will then look like this: 
![Screenshot_20200706-094119](https://user-images.githubusercontent.com/43148954/86568272-e7875280-bf6c-11ea-9700-76a678d5ae73.png)

The same thing other way around: 
![Screenshot_20200706-094506](https://user-images.githubusercontent.com/43148954/86568666-7bf1b500-bf6d-11ea-8c20-5d4901b0ee49.png)

After tapping the other text field, the same site with "Test" in the title field will look like this: 
![Screenshot_20200706-101145](https://user-images.githubusercontent.com/43148954/86571090-32a36480-bf71-11ea-9fcc-b8ecf263009e.png)

Other way around: 
![Screenshot_20200706-101336](https://user-images.githubusercontent.com/43148954/86571236-65e5f380-bf71-11ea-8e1c-e87012abb60d.png)
As you can see, the text is of the same (or almost same) color as the background.

When I switch the night mode on a different tab and then switch to an existing issue, it's to look like this: 
![Screenshot_20200706-091456](https://user-images.githubusercontent.com/43148954/86566079-4fd43500-bf69-11ea-859b-28975d238ca0.png)

It happened once that the site looked as if the night mode was off, but when I selected a word, the word turned white, but the background was kept white as well. The rest of paragraph was unchanged. I was able to reproduce it the other way around: 
![Screenshot_20200706-093353](https://user-images.githubusercontent.com/43148954/86567619-ee619580-bf6b-11ea-8e81-cb8e32f62adb.png)

Selecting a word makes the entire paragraph turn white: 
![Screenshot_20200706-092758](https://user-images.githubusercontent.com/43148954/86567117-18668800-bf6b-11ea-804b-56741d1b6503.png)

(See the previous screenshot for other way around.)

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next) ,these bugs are fixed
