### ISSUE TITLE
browser crashes on landscape

### ISSUE THREAD

**Issue by suzukar** [kiwibrowser/src#133]
System info: Android Version: 10 (API 29)
Device: samsung     SM-G9750
App Version: Kiwi-115617514-arm64

kiwi browser does not have the extensions installed and stays the default. The program crashes every time the browser switches to a landscape state.

**These following steps may be a solution thought, but I can't compile.**

The browser can switch directions normally when the following part of mController.onConfigurationChanged(newConfig) is commented out.

1. Locale locale = newConfig.locale;
2. if (!mLocale.equals(locale)) {
3. if ((getController()!=null)&&(getController().getCurr entTab()!=null))
4. getController().getCurrentTab().reShowGeolocationP ermissionsPrompt();
5. mLocale = locale;
6. }

The role of some codes
The Locale object can get some properties related to the configuration.
mLocale is the local object of the current application, and locale is the locale object contained in the new incoming settings.
This code assigns the program's locale to the newly changed configuration locale
Looking at the assignment of mLocale, it was found that mLocale was not assigned, causing the program to crash.”

**Comment by MistarMuffin** [comment]
This is happening on my LG G8X also on Android 10.

**Comment by suzukar** [comment]
Fixed

**Comment by kiwibrowser** [comment]
Thanks for confirming @suzukar !
@MistarMuffin don't hesitate if you still have the issue
