### ISSUE TITLE
Night Mode by default feature (for Tablets)

### ISSUE THREAD

**Issue by shuvashish76** [kiwibrowser/src#138]
Each time I restart the app, the inbuilt Night Mode disable automatically.

I know there are alternatives to it, like [darkreader](https://github.com/darkreader/darkreader) & [Midnight-Lizard](https://github.com/Midnight-Lizard/Midnight-Lizard) but they are not as good as kiwibrowser inbuilt dark mode.

It would be nice if there would be a **Night mode by default** option just like Desktop mode by default (`Settings>Accessibility>Desktop mode by default`)option.

I'm using browser version [77.0.3865.116](https://github.com/kiwibrowser/src/releases/tag/115617514) on lenovo tab4 8plus (TB-8704X), stock os, android 8.1.0

thankyou🙏🏿

ref: https://github.com/kiwibrowser/android/issues/130 #

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
