### ISSUE TITLE
How to use kiwibrowser sync extension?

### ISSUE THREAD

**Issue by shuvashish76** [kiwibrowser/src#139]
https://github.com/kiwibrowser/sync

There are no releases, like `.srx` type files to load in browser.
Then how to use this extension?

**Comment by zzzsyyy** [comment]
floccus doesn't work

**Comment by Shihabus-Sakib-Rad** [comment]
I have been using floccus for about 6 months. WebDAV. 
I sync bookmarks with firefox and brave on Windows

**Comment by d3ward** [comment]
Floccus officially support Kiwi , for now is the best solution to sync Kiwi with others browser
