### ISSUE TITLE
Kiwi Browser can't be used to play Stadia.com games

### ISSUE THREAD

**Issue by titooo7** [kiwibrowser/src#141]
Chromium android browser can be used to play Stadia if you open stadia.google.com on desktop mode (or if you use an user agent switcher extension). However that's not the case with Kiwi Browser.... 

If you click the play button then you just get a black screen and no stream is received till it times out after 2 minutes approximately. It doesn't matter if you use an extension to force vp9 or h264, no stream is received.

It's a shame since Kiwi browser is the only Chromium based Android browser with vp9 decode profiles (which means it could be used to play getting the 4K stream).

I guess the cause might be Kiwi Browser using a very old Chromium branch, but I wanted to report the bug just in case

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
