### ISSUE TITLE
"Offer to translate websites in a different language" doesn't work in any websites

### ISSUE THREAD

**Issue by AlexMnrs** [kiwibrowser/src#143]
![Screenshot_2020-08-01-17-01-12-177_com kiwibrowser browser](https://user-images.githubusercontent.com/10886760/89104321-d79e4980-d418-11ea-86d1-01ea0c5f8539.jpg)

Setting is enabled by default but it doesn't work in any websites.

Device: Xiaomi Mi9
OS: Android 10 (MIUI 11)

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
