### ISSUE TITLE
Can't load extracted folder as extension

### ISSUE THREAD

**Issue by Cyberavater** [kiwibrowser/src#145]
As a result the .zip is extracted in the cache and gets deleted randomly after some time.
https://github.com/Sainan/Universal-Bypass/issues/1387

Possible workaround; Having an option (enabling) which extracts and loads the extension from a permanent folder (a non-cache folder of the app).

**Comment by Delphox** [comment]
A workaround to avoid the cache deletion issue is packaging the extension folder into a CRX via the Pack Extension option and then installing the resulting CRX (putting the full path to the folder on Kiwi is a bit clunky but the "copy path" option on Solid Explorer helps with that; or you can do it on PC).

**Comment by Cyberavater** [comment]
> A workaround to avoid the cache deletion issue is packaging the extension folder into a CRX via the Pack Extension option and then installing the resulting CRX (putting the full path to the folder on Kiwi is a bit clunky but the "copy path" option on Solid Explorer helps with that, or you can do it on PC).

Thanks!

**Comment by Delphox** [comment]
On another note, if you wanna use Universal Bypass on Kiwi I'd actually recommend using the Edge version's CRX, as it has Edge store's update URL on its manifest so it should auto-update unlike the Chromium ZIP release which has no update URL at all. [Here's a link to download it through Edge webstore's API](https://edge.microsoft.com/extensionwebstorebase/v1/crx?response=redirect&&acceptformat=crx3&x=id%3Dckiidekccfgninkobmmofopbbdgdclgg%26installsource%3Dondemand%26uc).

Kinda wish Kiwi could download Edge addons natively but I assume it's tricky to spoof as I already tested and a simple user-agent spoof isn't enough like it is on Opera's addon store. So it's prolly out of scope.

**Comment by Delphox** [comment]
(tagging @kiwibrowser to check if he agrees or if I'm missing something and it's actually doable)

**Comment by Cyberavater** [comment]
Yes, it'd be nice if Kiwi could download Edge add-ons natively. Should I open a new issue regarding that?

**Comment by kiwibrowser** [comment]
The separate issue is better @Cyberavater 
(as a side-note, I'm not familiar at all with how the store for Edge add-ons is working)

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
