### ISSUE TITLE
Avaibility in playstore? 

### ISSUE THREAD

**Issue by LifeIsStrange** [kiwibrowser/src#15]
When will up to date (latest chromium) kiwi be available on Android playstore?

Thank you for your hardwork, you are really the author of the best Android browser

**Comment by kiwibrowser** [comment]
In about a week

**Comment by Adrymate9** [comment]
can you tell me how can i download the latest version of kiwi? I appreciate you.

**Comment by muznyo** [comment]
Will it be a big update?

**Comment by LifeIsStrange** [comment]
@muznyo honestly having an up to date chromium (so free performance gain) is already big enough for me.

**Comment by Adrymate9** [comment]
But when will it update? That is the important thing!

**Comment by LifeIsStrange** [comment]
@kiwibrowser up :)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> In about a week

playstore shows latest update was back in october 2019

**Comment by LifeIsStrange** [comment]
> > In about a week
> 
> playstore shows latest update was back in october 2019

Indeed but the project lack human resources. 
The original author is currently working on it (and is collaborating with alternative chromium browsers) to rebase the codebase toward a newer Chrome e.g M85 vs M77. 
It should be done at least in the following months

**Comment by xlollomanx** [comment]
> > > In about a week
> > 
> > 
> > playstore shows latest update was back in october 2019
> 
> Indeed but the project lack human resources.
> The original author is currently working on it (and is collaborating with alternative chromium browsers) to rebase the codebase toward a newer Chrome e.g M85 vs M77.
> It should be done at least in the following months

Latest version is based on Chrome 85 :)

**Comment by kiwibrowser** [comment]
> > > > In about a week
> > > 
> > > 
> > > playstore shows latest update was back in october 2019
> > 
> > 
> > Indeed but the project lack human resources.
> > The original author is currently working on it (and is collaborating with alternative chromium browsers) to rebase the codebase toward a newer Chrome e.g M85 vs M77.
> > It should be done at least in the following months
> 
> The latest version released on github is based on Chrome 85 :)

It's just UA change for now ;)
It's still 77

**Comment by LifeIsStrange** [comment]
@kiwibrowser you've published an update on the playstore :0 is it still just the UA or is it real chromium 85??

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Yes, According to kiwi://version


Kiwi	source branch is Chromium 77.0 + Kiwi backported fixes, will show 85.0.4183.101 to websites for compatibility reasons (64-Bit)

JavaScript	V8 6.8.275.15

User-Agent	Mozilla/5.0 (Linux; Android 10; Mi 9 Lite) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.101 Mobile Safari/537.36

**Comment by LifeIsStrange** [comment]
It's still the user agent then, sad :/

**Comment by Dev-i-l** [comment]
@LifeIsStrange you can close this issue now, as kiwi will now update only the user agent strings and work on kiwi next which will be automatically rebased to latest chromium, will start in april 2021 kiwi's anniversary

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> @kiwibrowser you've published an update on the playstore :0 is it still just the UA or is it real chromium 85??

Yes, According to kiwi://version


Kiwi	source branch is Chromium 77.0 + Kiwi backported fixes, will show 85.0.4183.101 to websites for compatibility reasons (64-Bit)

JavaScript	V8 6.8.275.15

User-Agent	Mozilla/5.0 (Linux; Android 10; SM-G925F Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.101 Mobile Safari/537.36
