### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Deepak1202** [kiwibrowser/src#150]
How can we use our google analytics key into this project?

**Comment by kiwibrowser** [comment]
You need to add Google Analytics in the AndroidManifest.xml in the chrome/android folder but it's going to be tough to put firebase or analytics (since there is no implementation of that in Kiwi)

**Comment by abhishek9832** [comment]
so what's the google analytics mentioned @ https://kiwibrowser.com/privacy-policy/  ..is this related to google analytics meant for www.kiwibrowser.com or the KIWI browser app ? In the chromium/src we could see analytics.js and ./third_party/analytics/google-analytics-bundle.js ? what are they for

**Comment by kiwibrowser** [comment]
https://kiwibrowser.com/privacy-policy/ applies to the kiwibrowser.com website only. It's a WordPress blog and there is Google Analytics inside.

The file you refer to is from Chrome OS (which is based on Chromium, like Kiwi):
https://github.com/kiwibrowser/src/blob/b1ea3ea95d8ac15fc0b49acd83ba2f8b1aaa8d2b/chrome/common/extensions/docs/templates/articles/analytics.html

It's for Chrome Apps, it's not active in Kiwi and there is no way to activate that.
The only way you can do is by adding Google Analytics to dependencies, pull or copy dependencies (I guess Firebase as I'm not too familiar with it ?) and add it to ChromeApplication.java

I'll close this for now, best is to locate the AndroidManifest.xml and try to add it there, and then you can add it (it will complain about the missing .jar, which you have to add then)
