### ISSUE TITLE
Tab switcher + bottom toolbar option is missing.

### ISSUE THREAD

**Issue by Drakim42** [kiwibrowser/src#151]
The tab switcher is missing ever since I installed Kiwi. The bottom toolbar option is also missing, but isn't a problem since I never use it. Links to screenshots are below.

https://ibb.co/Cbdj9S5 
https://ibb.co/dQHgx9B
https://ibb.co/zJyLtWw
https://ibb.co/vPY2Zpf

**Comment by Dev-i-l** [comment]
bruh it's a toggle you can enable bottom toolbar in accessibility, and enable horizontal tab switcher in chrome://flags . you can close this issue then

**Comment by Drakim42** [comment]
I can't enable the bottom toolbar option in accessibility, since it isn't there for me. The tab switcher icon is also missing. Enabling or disabling the horizontal tab switcher flag changes how the tab switcher looks once it's open. It doesn't make the icon itself appear or disappear. Links to screenshots are below.

https://ibb.co/Cbdj9S5 
https://ibb.co/dQHgx9B
https://ibb.co/zJyLtWw
https://ibb.co/vPY2Zpf

**Comment by mindwarp42** [comment]
Sorry to revive an older bug: this only affects Kiwi running on Android tablets. My Samsung Galaxy Tab A (2019) looks like this, while my Moto G Power phone has the tab switcher button and the option to turn on a bottom toolbar. I'm another who doesn't care about the latter, but having the tab switcher button would be nice if only to know how many tabs are open (I'm aware of how to switch tabs by scrolling through the tabs themselves, although if a lot are open they can pile up and, for lack of a better way to describe it, hide in the stack of opened tabs when scrolling).

**Comment by CEHitchens** [comment]
Same here. Galaxy Tab S2 running LineageOS and Kiwi Browser vGit210216Gen570536402
- no tab switcher visible
- no option to place URL bar at bottom of screen

**Comment by Oranko** [comment]
Please try the latest version

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
