### ISSUE TITLE
ERROR: The only supported distros are Ubuntu and Debian(and Only x86)?

### ISSUE THREAD

**Issue by disdaogitacc** [kiwibrowser/src#152]
hi and thanks for the app. bruh i've been cloning about 4GB and now i'm facing this error? is this the end?
i use arch x86_64 btw

**Comment by kiwibrowser** [comment]
You can build from any Ubuntu or Debian x64 machine (I think it's the same with base Chromium).

Ubuntu works fine for example

**Comment by disdaogitacc** [comment]
> You can build from any Ubuntu or Debian x64 machine (I think it's the same with base Chromium).
> 
> Ubuntu works fine for example

is there any workaround to build on other distros? (like commenting that in install-build-deps.sh)

**Comment by disdaogitacc** [comment]
sorry for the noobiness
https://chromium.googlesource.com/chromium/src/+/master/docs/linux/build_instructions.md#Arch-Linux

**Comment by kiwibrowser** [comment]
Google used Ubuntu internally (Goobuntu) and gLinux so your experience with Arch Linux may be rough.

One alternative is to use the GitHub Actions builds (they are free, but only 6 hours, and a 2-core build can take 20h) or a Ubuntu VM (e.g. Google Cloud, but that can get pretty expensive)
