### ISSUE TITLE
Show Chromium versions it is based on

### ISSUE THREAD

**Issue by TheEvilSkeleton** [kiwibrowser/src#155]
It's hard to tell what Chromium version it's based on. Could you put those informations in the [Releases](https://github.com/kiwibrowser/src/releases) page and the `About Kiwi` section in the Kiwi app?

**Comment by kiwibrowser** [comment]
It's 77 variant, I will add a message yes, probably tomorrow. I just updated the UA yet

**Comment by TheEvilSkeleton** [comment]
Alright, thank you for the quick answer.

**Comment by Sujan319** [comment]
Its showing 85 on my  device.look-->
![Screenshot_20200908-142235](https://user-images.githubusercontent.com/67813061/92455507-5f792f80-f1df-11ea-8d24-ffd96b9710f1.png)

**Comment by Sujan319** [comment]
@kiwibrowser It is showing 85 on my device.


![Screenshot_20200908-142235](https://user-images.githubusercontent.com/67813061/92457118-7456c280-f1e1-11ea-867c-c3fefbc08117.png)

**Comment by kiwibrowser** [comment]
I fixed it in latest build
