### ISSUE TITLE
kiwi://bookmarks

### ISSUE THREAD

**Issue by zzzsyyy** [kiwibrowser/src#156]
Hi , Thanks for this great app , please add kiwi://bookmarks , it's really useful , thanks.

**Comment by yeezylife** [comment]
yeah，I wanna set my startpage to bookmarks,but couldn't find how..

**Comment by Delphox** [comment]
Check `chrome-native://bookmarks` (tap the blue suggestion as hitting enter will do as google search)

**Comment by zzzsyyy** [comment]
There is no blue suggestion  after tapping

**Comment by Delphox** [comment]
I mean when you type ``chrome-native://bookmarks``, you should be greeted with this:
![_20201016_113328](https://user-images.githubusercontent.com/5883538/96271974-03af7c80-0fbd-11eb-86d4-9186e0b725a2.JPG)

You tap the second option (which has blue text) as hitting enter on the keyboard or tapping the top one will do a search instead.

**Comment by zzzsyyy** [comment]
thank you，but there is no second suggestion .like this
![1620b95460bc08a38adf92721ba0de2](https://user-images.githubusercontent.com/59917878/96329395-ecd15e80-107e-11eb-8ff1-e632c5777e5c.jpg)

**Comment by Delphox** [comment]
Oh, turns out you have to search it first so it gets suggested from the history (the blue text) the next time you type it. Kinda weird.

**Comment by Oranko** [comment]
Present in the latest version
