### ISSUE TITLE
Extension conflict for Kiwi Browser 77.0.3865.92

### ISSUE THREAD

**Issue by danny0838** [kiwibrowser/src#157]
I'm the developer of [Content Farm Terminator](https://chrome.google.com/webstore/detail/content-farm-terminator/lcghoajegeldpfkfaejegfobkapnemjl) (CFT). It seems that there's some conflict when CFT 3.12.0 is installed and enabled on Kiwi Browser 77.0.3865.92, that opening any web page halts forever (https://github.com/danny0838/content-farm-terminator/issues/44), while installing CFT on Google Chrome (<= 85.0.4183.102) and Firefox works well.

It seems that Yandex browser (20.80) has same issue.

I'm not familiar with mobile debugging. Can you provide some hints about what extension API is not working?

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
