### ISSUE TITLE
Can not debug the extensions of Kiwi browser in Google Developer Tool

### ISSUE THREAD

**Issue by mkpatel42** [kiwibrowser/src#158]
When I add extension in Kiwi Browser, it doesn't work expected. So, I want to debug the extension / website in google chrome remotely using Google Developer tool. But Google Developer Tool is not working for Kiwi Browser. It shows all the tabs but doesn't display console and DOM elements. Can you please let me know how to debug this? Also Is there any other way to debug the website which is loaded on Kiwi Browser?

**Comment by kiwibrowser** [comment]
It's now fixed in chrome://inspect on Desktop

**Comment by CristiaanRojas** [comment]
Hello, I have the same problem, could you explain how I can open dev tools or some kind of console to see the errors as it could be done in a desktop web browser? I'm testing the compatibility of an extension with Kiwi, and it seems to load libraries like Jquery, Bootstrap and others, but there is a certain animation that doesn't work and I'd like to find out why.

**Comment by CristiaanRojas** [comment]
Update: I was able to open the developer tools in the desktop web browser connected to the extension in Kiwi using 'chrome: // inspect / # devices'. Now the problem I have is that when trying to execute the javascript code of the extension in Kiwi it throws certain syntax errors. For example, the null propagation operator (?.) Does not recognize it, and it shows me the following message 'Uncaught syntaxerror unexpected token.', Also, when commenting on the block where the above error occurs I find similar errors elsewhere in the code, which works without errors in the desktop web browser. Why would this happen?

**Comment by CristiaanRojas** [comment]
Could it be due to the underlying JavaScript engine? What version of ecmascript can Kiwi run?
