### ISSUE TITLE
Requesting to update the user interface to latest chromium

### ISSUE THREAD

**Issue by Sujan319** [kiwibrowser/src#159]
Its great to see kiwi is back on track.however,there are some features that need to be updated.If you have time,plz look at these features.
1.if you can update the UI (like the settings menu which looks not so good in dark/night mode,the ui elements on url bar like home,tab ,three dot menu - make it more rounded square)
2.in site settings>javascript, add javascript exceptions
Actually if you have enough time then implement the latest chromium UI ,if you do that will be great.
One more thing if you can add support for custom font from user given font,that will be fantastic.

**Comment by d3ward** [comment]
Check out latest Kiwi builds [src.next](https://github.com/kiwibrowser/src.next)
