### ISSUE TITLE
Translations in directory "src/chrome/android/java/strings/translations" not getting generated for .xtb files

### ISSUE THREAD

**Issue by Deepak1202** [kiwibrowser/src#160]
I have tried adding new string in "**android_chrome_strings.grd**" file and run the build process, but translations in **.xtb** files are not getting generated automically. We can not add it mannually because there are some some auto generated number as id. The final strings file in **"out"** folder consist english language in all translated files.

Can you guide me if I am missing any step which generates translation in .xtb files? or somehow we can find generated ids in .xtb files, so that we can add mannual translation to it.

**Comment by kiwibrowser** [comment]
Kiwi uses the standard Android translation strings, which makes it easier to maintain

https://github.com/kiwibrowser/src/blob/master/chrome/android/java/res/values-it/strings.xml

Simply add the strings to values-*
