### ISSUE TITLE
Crashes (Aw! Snap) in non-incognito browsing

### ISSUE THREAD

**Issue by kiwibrowser** [kiwibrowser/src#164]
Appears to be Script cache in V8 that is corrupted since the build has been done from scratch (perhaps due to rebuilt v8 cache ?!)

Suspecting it could be simplecache otherwise (though unlikely)

**Comment by kiwibrowser** [comment]
Bumped V8 script version

**Comment by AndyTheFactory** [comment]
Clearing app cache seems to fix this issue

**Comment by kiwibrowser** [comment]
Closing for now, as bumped V8 + introduced https://github.com/kiwibrowser/src/commit/a329efc2cde09971ea92fec000a6259ed940f1ce that will come soon in deployed versions
