### ISSUE TITLE
Kiwi browser failed to call qq one-key login

### ISSUE THREAD

**Issue by Chaniug** [kiwibrowser/src#165]
Kiwi browser cannot call mobile qq one-key login. My qq version is the latest version, and some web pages that need to call qq login will display this kind of let me install the latest qq version.
 @![85295f1059182ebc5f18a326d0687716](https://user-images.githubusercontent.com/35595273/92992874-94bda000-f4b3-11ea-9dc4-ed7fc268280f.jpg)

**My mobile QQ version**
![Screenshot_20200913_113557_com tencent mobileqq](https://user-images.githubusercontent.com/35595273/93009648-22979a80-f549-11ea-9df3-e4e85282eeb4.jpg)

**A strange solution：**
If you set the kiwi browser as the default browser, use another browser (such as Firefox) to open the webpage that requires QQ login, and then jump to kiwi, and kiwi can successfully log in to the website.
Test page：https://wj.qq.com/
Problem recurring：_gif picture display, please save and view_
![Problem recurring](https://user-images.githubusercontent.com/35595273/93010080-0a764a00-f54e-11ea-865d-f90d465956e8.gif)

**Comment by Chaniug** [comment]
Can you fix this bug? Brother~

**Comment by qwe0099001** [comment]
Yes

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
If the bug still persist , you can open a new issue on the repo
