### ISSUE TITLE
Missing Chromium flag for freezing user agent

### ISSUE THREAD

**Issue by Syhlx** [kiwibrowser/src#166]
In the chrome://flags section, the following flag is missing: #freeze-user-agent.
This flag allows users to choose not to reveal too much information about their device.

The Chromium version used by Kiwi (85.0.4183.101) should have this flag baked in.

**Comment by Dev-i-l** [comment]
@Syhlx kiwi, as of now is only udating user agent, you can't expect flags/features from latest chromium. you can close this issue

**Comment by kiwibrowser** [comment]
@Syhlx Thanks, the flag will be added

**Comment by d3ward** [comment]
Check out latest Kiwi builds  on [src.next](https://github.com/kiwibrowser/src.next)
