### ISSUE TITLE
Can't inject content script from extension to page

### ISSUE THREAD

**Issue by K1DV5** [kiwibrowser/src#167]
I'm developing an extension which needs to listen for events on the page. So I'm using a content script which listens for those events and sends a message to the background script. Everything works on desktop chrome, but it doesn't under Kiwi. If it's a limitation of Kiwi's extensions support, is there a way around it?

**Comment by kiwibrowser** [comment]
Hello,

It's supported. It's possible to exchange information between background and content script (and extensions like uBlock Origin do it extensively) so it's a bug, do you have a more precise event you don't receive or a specific syntax ?

**Comment by K1DV5** [comment]
All is good now, I was trying to inject the content script code programmatically from the background script, using `tabs.onUpdated`, in order to detect click or contextmenu events. When I made it its own file and included it in the manifest, it worked without a problem. Thanks
