### ISSUE TITLE
[BUG]Rotating a web page causes a crash

### ISSUE THREAD

**Issue by hshx123** [kiwibrowser/src#168]
- [x] After searching, the same issues were not found

    

When I open any web page and rotate it about **40 times** , the browser crashes

![](https://cdn.jsdelivr.net/gh/hshx123/cdn@latest/2020/09/13/20200913232330453.jpg)
_This is a demonstration video(The video is cropped)_
![](https://cdn.jsdelivr.net/gh/hshx123/cdn@latest/2020/09/13/20200913233856088.gif)

    

**Version information**
phone: Honor 9X CPU: Kylin810
![](https://cdn.jsdelivr.net/gh/hshx123/cdn@latest/2020/09/13/20200913234145381.jpg)

In the latest version of **Chrome** , no this problem

**Comment by hshx123** [comment]
This problem is easy to happen when using a Qualcomm Snapdragon855 phone(IQOO) 
**About 4 times**
![](https://cdn.jsdelivr.net/gh/hshx123/cdn@latest/2020/09/15/20200915003111288.jpg)

**Comment by kiwibrowser** [comment]
Might have found !
https://github.com/kiwibrowser/src/commit/a329efc2cde09971ea92fec000a6259ed940f1ce

Will test deploying

**Comment by Y-T-G** [comment]
I have this issue since updating to Android 10. I am currently running AOSiP DerpFest ROM. But, for me the page immediately crashes on first rotation.

**Comment by kiwibrowser** [comment]
Epic @Y-T-G 
Thank you thank you thank you !

I'm looking into the trace

**Comment by kiwibrowser** [comment]
FUNC 2d470d4 1e0 0 sandbox::Trap::SigSys(int, siginfo*, ucontext*)

Seems likely a seccomp violation, will see

**Comment by kiwibrowser** [comment]
(the sandbox is here to crash when an action is not explicitly whitelisted, it's a security feature of the browser)

**Comment by kiwibrowser** [comment]
Provisional fix https://github.com/kiwibrowser/src/commit/2ae02089dd349ba1acfec4fe7a124e4b1330bb07

**Comment by kiwibrowser** [comment]
Should be fixed in https://github.com/kiwibrowser/src/commit/6bd7fb7dcdb428132512512e490ea2a7dd761861

**Comment by Y-T-G** [comment]
@kiwibrowser Can confirm. It's fixed now. Thank you.

**Comment by kiwibrowser** [comment]
Thank you for the update!
