### ISSUE TITLE
Scrolling problem

### ISSUE THREAD

**Issue by K1DV5** [kiwibrowser/src#169]
There is a problem on some sites (noted on developer.chrome.com) where the scroll speed is about twice as fast as the finger swipe. It also refuses to scroll sideways (noted on worldometers.info/coronavirus table).

**Comment by K1DV5** [comment]
I'm not familiar with this codebase but I think the problems are:
- when scrolling sideways, an opposite but equal offset is added to the main offset, making the net offset 0. This can be noticed on pages having wider tables than the viewport.
- when scrolling up or down, an equal offset is added to the main offset. This makes the net offset twice as large, making the scrolling twice as fast. This doesn't always happen though, just on some pages.

**Comment by K1DV5** [comment]
I want to add my finding that this problem occurs on Galaxy J4 core (Android 8.1 go) and everything is smooth on Galaxy S3 (custom Android 7). I think this issue and #206 are related.

**Comment by K1DV5** [comment]
Another finding: this problem occurs only when the "text rewrap/reflow" option in accessibility settings is on.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
