### ISSUE TITLE
facing issue with newly added dependency in kiwi : central directory and file header inconsistent

### ISSUE THREAD

**Issue by mitngpl** [kiwibrowser/src#171]
I have added new dependency and while creating apk I am seeing this issue with the newly added dependency.
seems some issue with ijar while extracting interfaces.jar from classes.jar under analytics.aar.

FAILED: lib.java/third_party/android_deps/analytics_core_java.interface.jar 
python ../../build/gn_run_binary.py clang_x64/ijar gen/third_party/android_deps/analytics_core_java/classes.jar lib.java/third_party/android_deps/analytics_core_java.interface.jar
central directory and file header inconsistent

Any leads will be helpful.

**Comment by mitngpl** [comment]
Any leads on this behaviour of ijar ?

**Comment by mitngpl** [comment]
https://chromium.googlesource.com/chromium/src/third_party/+/dcf18f14bd22a23698831957481981190f3baf13

issue was with kiwi  thirdparty ijar while processing androidx classes.jar files.
kiwi can consider updating third party.

Anyways, Thanks for your reply :)

**Comment by kiwibrowser** [comment]
@mitngpl Thanks for sharing the solution, I'm in the process of updating to AndroidX and your issue and discovery was helpful :)
