### ISSUE TITLE
Facebook messages tab always asks to use messenger app

### ISSUE THREAD

**Issue by avbobylev** [kiwibrowser/src#173]
In mobile mode facebook messages tab always asks to use their messenger instead of showing messages. It was one of the key kiwi features for those who dont want to use facebook standalone apps, but now its broken. Possibly related to issue #23

**Comment by kiwibrowser** [comment]
You're right, this probably needs a revert.
However I'm wondering why Chrome is not redirected (!) and what is the criteria that Facebook uses to detect, but this is relatively severe yes.

**Comment by kiwibrowser** [comment]
A fix is coming

**Comment by kiwibrowser** [comment]
Landed
