### ISSUE TITLE
AMP and external applications

### ISSUE THREAD

**Issue by lpuglia** [kiwibrowser/src#175]
There seems to be some sort of misbehavior when an AMP link has an associated external application, this is what I'm facing right now:

* Settings/Privacy/Remove AMP ❌
    * Clicking on a NON AMP link open the associated APP
    * Clicking on an AMP link DOES NOT open the external APP but just open the AMP Link in the browser

* Settings/Privacy/Remove AMP ✔️
    * Clicking on a NON AMP link open the associated APP
    * Clicking on an AMP link DOES open the external APP but ONLY ONCE, the second time you click on the same link or other similar AMP link nothing happens

I'm using the latest version from the play-store, i can produce a video if you need it

**Comment by KaKi87** [comment]
App associations cannot work on AMP links when AMP is not disabled.
Please post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
