### ISSUE TITLE
Website landing verification error

### ISSUE THREAD

**Issue by blue2018** [kiwibrowser/src#181]
![Screenshot_20200921-115900_cropped](https://user-images.githubusercontent.com/13889354/93762396-1bb9f900-fbd5-11ea-8e85-4806ddc146cd.png)
![Screenshot_20200921-115937_cropped](https://user-images.githubusercontent.com/13889354/93762415-22e10700-fbd5-11ea-9452-e22af17d622b.png)

I can't verify by landing on this page. When I swiped right, it returned error. It seems that every attempt will get a different error. But I can login with Chrome without any problems. Any suggestion?
The website url is https://www.yun.cn/#/user/login?callback=%2F
My Kiwi browser's version is git200915.

**Comment by blue2018** [comment]
Please fix this error, thank you very much!

**Comment by kiwibrowser** [comment]
The request is blocked by https://cf.aliyun.com/nocaptcha/analyze.jsonp

I don't know why and how.It just says "非常抱歉，这出错了(error:rzJQu6)" in analyze.jsonp
"code":300,"value":"block"

**Comment by blue2018** [comment]
> The request is blocked by https://cf.aliyun.com/nocaptcha/analyze.jsonp
> 
> I don't know why and how.It just says "非常抱歉，这出错了(error:rzJQu6)" in analyze.jsonp
> "code":300,"value":"block"

Thanks for your reply! I have no idea, too. I just know if I use chrome to visit this page, no error will be shown, and I can successfully pass the verification. It's strange.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
