### ISSUE TITLE
Crashed gpu thread

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [kiwibrowser/src#183]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Revision: '0'
ABI: 'arm64'
name: Chrome_IOThread  >>> com.kiwibrowser.browser <<<
uid: 10322
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:gpu_data_manager_impl_private.cc(880)] GPU process isn't usable. Goodbye.
'
    x0  0000000000000000  x1  00000000000046c2  x2  0000000000000006  x3  0000007068e26ac0
    x4  fefeff6efefefeff  x5  fefeff6efefefeff  x6  fefeff6efefefeff  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  b7da936c6dbc0339  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 000000706a5bbf42  x14 0000000000000009  x15 0000000000000009
    x16 000000715bca7738  x17 000000715bc86180  x18 000000705f9d0000  x19 00000000000045c7
    x20 00000000000046c2  x21 00000000ffffffff  x22 000000715bca2508  x23 000000706e3c2000
    x24 0000000000000004  x25 0000007068e28020  x26 0000007068e26ba0  x27 000000706e2684b0
    x28 0000000000000002  x29 0000007068e26b60
    sp  0000007068e26aa0  lr  000000715bc3786c  pc  000000715bc37898

backtrace:
      #00 pc 0000000000073898  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 745f6147935e4ea7837d3e6fc6def1e1)
      #01 pc 000000000227fca0  /data/app/com.kiwibrowser.browser-XuVMK-t1srKOlPMp3zGBhA==/lib/arm64/libchrome.so!libchrome.so (offset 0xe91000) (BuildId: 6c395a8eeb07af4ad758370262e8aeb97e508e0c)

**Comment by kiwibrowser** [comment]
Hello,

I'm glad you found this crash, it's the most common crash in Kiwi (according to the Play Store), it's really really really obscure, and I couldn't contact any user about it, as in the Play Store you cannot reply to crash reports.

Do you know a way to reproduce the issue, or was the browser behaving strangely before this was happening ?

Thank you very much,

**Comment by kiwibrowser** [comment]
May be fixed by https://github.com/kiwibrowser/src/commit/22f731876b93f2cba102860bb4447b9cee535112

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Excuse me, I can't give more information since updated and cannot reproduce now. Keep up the good work. Thank you anyway.
