### ISSUE TITLE
Failed to load extension in private mode

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [kiwibrowser/src#184]
I used [PDF Reader](https://add0n.com/pdf-reader.html) extension to read PDF online, but when I open an online PDF in private mode, the extension gives me ERR_BLOCKED_BY_CLIENT responce. Is it possible to fix that?

Try [this file](https://github.com/mozilla/pdf.js/blob/gh-pages/web/compressed.tracemonkey-pldi-09.pdf) ([mirror](https://cdn.jsdelivr.net/gh/mozilla/pdf.js@gh-pages/web/compressed.tracemonkey-pldi-09.pdf)) for test.

**Comment by KrasnayaPloshchad** [comment]
@kiwibrowser

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
