### ISSUE TITLE
Can you add these features?

### ISSUE THREAD

**Issue by jamesalpera** [kiwibrowser/src#185]
Can you add the feature to set the download location to the cloud?
Please add the automatic translation feature of web pages to the browser without opening a new page. Like Chrome last version Thanks.

**Comment by irwan-batra** [comment]
this is never gonna happen unless he won't gonna Buy translator API. it is at quite high price.kiwi doesn't make much money.

**Comment by Oranko** [comment]
The native translate feature is now available in the latest update
