### ISSUE TITLE
swipe left/right to navigate history collides with left/right scroll

### ISSUE THREAD

**Issue by marcusatiliusregulus** [kiwibrowser/src#189]
swiping left/right to go through the history is an amazing feature but it creates a problem: when i want to scroll left or right on a webpage i have to be extremely careful to not make the swipe too long and trigger the history navigation.

there are several ways i can imagine to impove the feature (but im not sure which are even possible to implement. ordered by my preference):

1. disable history navigation when drag in left/right scrollable website area registered
2. add a disable history navigation option to the hand button (long press, double tap, etc)
3. before history navigation is executed an arrow is shown indicating that history navigation will be executed if the swipe continues. if it would be possible to also blend in a button to toggle the feature that would be great (in this case the history navigation would not be triggered when the toggle is on, but the button to toggle it would still be shown to reenable the feature)
4. simply add the option to toggle this feature to the triple-dot menu

**Comment by marcusatiliusregulus** [comment]
another idea:
+ give option to navigate history when swiping on the menubar (instead of switching tabs)

**Comment by kiwibrowser** [comment]
@marcusatiliusregulus This is a though one, I agree the option should be the best solution.
Do you have example of page or usage where the left or right gestures are significantly colliding with your standard navigation ?
Perhaps an alternative solution would be to make the zone smaller ?

**Comment by marcusatiliusregulus** [comment]
since i reinstalled the app yesterday i didnt encounter the problem anymore but this doesnt mean its gone for good because it wasnt there all the time before either...

the problem was most noticible on google maps or openstreetmaps and sites that embedded them (where you have to use two fingers to move the map). furthermore when there are left/right scrollable text parts like [here](https://github.com/kiwibrowser/src/issues/38) (the problem was that the history navigation was triggered very soon after starting to scroll. when the end of the scrollable is reached and you dont stop scrolling immediately hist nav is triggered too, which is very annoying but i guess understandable (since in this direction its not scrollable anymore) and not the problem i talked about)

**Comment by marcusatiliusregulus** [comment]
on jobs.netflix.com the "latest from netflix" listing cannot be swiped left or right easily without triggering the history nav. (obviously you need something before and after this page in your tabs history!)

**Comment by kanari3** [comment]
@kiwibrowser 
On my device, up and down scrolling is perceived as a left and right swipe 😇
I'd like to be able to turn it on and off in settings.

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).

**Comment by marcusatiliusregulus** [comment]
yup, it now works as i would want it. thanks
