### ISSUE TITLE
Chromium 86 has released stable 

### ISSUE THREAD

**Issue by LifeIsStrange** [kiwibrowser/src#192]
86 would be better than 85 because the backforward cache is a really significant optimization!
https://www.phoronix.com/scan.php?page=news_item&px=Google-Chrome-86

**Comment by kiwibrowser** [comment]
That one looks good!

**Comment by LifeIsStrange** [comment]
@kiwibrowser there's still no time estimate of when will kiwi complete the rebasing?

**Comment by irwan-batra** [comment]
there's never rebase being done by developer.what you saw is only useragent

**Comment by kiwibrowser** [comment]
@irwan-batra @LifeIsStrange 2021

**Comment by kiwibrowser** [comment]
@irwan-batra @LifeIsStrange beginning of 2021

**Comment by Oranko** [comment]
Browser has now been updated to the latest version
