### ISSUE TITLE
Blitztactics website not working properly.

### ISSUE THREAD

**Issue by shuvashish76** [kiwibrowser/src#197]
Chess puzzle website https://blitztactics.com not working. The board is empty having no pieces.
source code of the site: https://github.com/linrock/blitz-tactics

It's working properly in old chrome browser (phone) Version 70.0.3538.110.
I suppose there must be many other similar websites which kiwi doesn't support.

![blitztactics](https://user-images.githubusercontent.com/48226312/95690122-192a4c80-0c33-11eb-9190-77973a24f19c.jpeg)

**Comment by Delphox** [comment]
Open `kiwi://flags`, search for `webassembly streaming` and set it to Enabled, then restart Kiwi.

**Comment by shuvashish76** [comment]
> Open `kiwi://flags`, search for `webassembly streaming` and set it to Enabled, then restart Kiwi.

Thanks😇. Now its working perfectly. I hope in future kiwi will make this by default for everyone without _Allowing mining of crypto-currencies_

For those who facing similar issue what I did is👇🏿

`kiwi://flags`
Search `webassembly streaming`
set it to `Enabled`
relaunch the app
`kiwi://restart`

**Comment by d3ward** [comment]
Working fine with latest builds
