### ISSUE TITLE
Suggestions for turning on incognito mode

### ISSUE THREAD

**Issue by SummerAfternoon** [kiwibrowser/src#198]
As a user who needs to turn on the incognito mode from time to time, it is really pleasant to be in the incognito mode when the browser is opened. I noticed that for UC browser, opera browser, etc., you can directly set to start in incognito mode on Android, but kiwi cannot. So I hope you can add a feature that can be started in incognito mode directly, just like adding the parameter "--incognito" on the computer to make chrome start in incognito mode.😊

**Comment by rururux** [comment]
kiwi already have "open in incognito" shortcut.
put in your homescreen, and open kiwi from there.
https://support.google.com/android/answer/9450271
