### ISSUE TITLE
Setup continuous integration

### ISSUE THREAD

**Issue by kiwibrowser** [kiwibrowser/src#20]
Setup Travis-CI to have continuous builds (in particular regarding pull requests)

**Comment by kiwibrowser** [comment]
Can also test GitHub Actions (may be better)

**Comment by kiwibrowser** [comment]
GitHub Actions seems to be much better due to high free usage limits

**Comment by SuperSandro2000** [comment]
Travis has also arm64, macos and windows in one CI.

**Comment by kiwibrowser** [comment]
Thanks for info, as long as the host platform is x86 or x64 everything is fine, we can build all variants using the cross-compilers

**Comment by kiwibrowser** [comment]
GitHub Actions may not be viable:
Updating files:  53% (286704/535133)
Updating files:  53% (286707/535133)
Updating files:  53% (286710/535133)
Updating files:  53% (286712/535133)
Updating files:  53% (286721/535133)
Updating files:  53% (286730/535133)
Updating files:  53% (286740/535133)
Updating files:  53% (286897/535133)
Updating files:  53% (286899/535133)
Updating files:  53% (287112/535133)
Updating files:  53% (288666/535133)
Updating files:  53% (288866/535133)
Updating files:  54% (288972/535133)
Updating files:  54% (289073/535133)
Updating files:  54% (289090/535133)
##[error]No space left on device


===
GitHub Actions: 14 GB of SSD disk space
Travis-CI offers 50 GB

The repo requires about 25 GB

**Comment by kiwibrowser** [comment]
Could also mount the repository using FUSE / Gitfs. Though performance may be terrible.

**Comment by kiwibrowser** [comment]
gitfs is a bad idea, testing an alternative where I disable swap to gain free disk space (about 8GB)
https://github.com/kiwibrowser/actions_test_project

**Comment by kiwibrowser** [comment]
Apparently working when deleting .NET framework
Should explore
https://github.com/marketplace/actions/android-emulator-runner

**Comment by kiwibrowser** [comment]
+ https://github.com/facebook/screenshot-tests-for-android

**Comment by kiwibrowser** [comment]
% time     seconds  usecs/call     calls      function
------ ----------- ----------- --------- --------------------
 23.04 1301.352213          67  19153349 _ZNSsC1ERKSs
 18.40 1039.385976          68  15277051 _Znwm
 17.93 1012.977895          68  14894471 _ZdlPv
 10.55  595.929595          68   8748362 _ZNSs4_Rep10_M_destroyERKSaIcE
  7.33  413.924912          68   6083516 memcmp
  5.36  303.047528          68   4424289 _ZNSsC1EPKcmRKSaIcE
  5.23  295.636605          68   4335066 _ZNSs6appendERKSs
  5.15  291.098380          67   4289822 _ZNSs6resizeEmc
  5.15  291.049920          67   4288123 _ZNSs12_M_leak_hardEv
  0.80   45.256698          67    665711 _ZNSs6appendEPKcm
  0.45   25.369469          68    373020 _ZNKSs7compareEPKc
  0.18   10.055929          68    146828 _ZNSsC1EPKcRKSaIcE
  0.15    8.704722          68    127893 memmove
  0.12    6.498876          68     94962 _ZNSs6assignEPKcm
  0.08    4.747010          68     69552 _ZSt29_Rb_tree_insert_and_rebalancebPSt18_Rb_tree_node_baseS0_RS_
  0.02    1.387312          67     20544 _ZNSs6assignERKSs
  0.02    1.228092          68     17944 _ZSt18_Rb_tree_decrementPKSt18_Rb_tree_node_base
  0.02    1.049604         122      8583 fread
  0.00    0.185933         109      1700 fopen
  0.00    0.167608          98      1699 fclose
  0.00    0.117229          68      1699 ferror
  0.00    0.001735         192         9 memset
  0.00    0.000317          79         4 __cxa_guard_acquire
  0.00    0.000282          70         4 __cxa_guard_release
  0.00    0.000275          68         4 atoi
  0.00    0.000259          64         4 _ZNSsC1ERKSsmm
  0.00    0.000259          64         4 _ZNKSs4findEcm
  0.00    0.000193          64         3 __cxa_atexit
  0.00    0.000192         192         1 sysconf
  0.00    0.000183         183         1 printf
  0.00    0.000152         152         1 __errno_location
  0.00    0.000142          71         2 getopt_long
  0.00    0.000137          68         2 strlen
  0.00    0.000135          67         2 atol
  0.00    0.000116         116         1 vfprintf
  0.00    0.000116         116         1 fwrite
  0.00    0.000105         105         1 chdir
  0.00    0.000099          99         1 fputc
  0.00    0.000090          90         1 snprintf
  0.00    0.000078          78         1 strerror
  0.00    0.000076          76         1 _ZNSsC1EmcRKSaIcE
  0.00    0.000073          73         1 _ZNSs7reserveEm
  0.00    0.000069          69         1 setvbuf
------ ----------- ----------- --------- --------------------
100.00 5649.176589              83024234 total

**Comment by kiwibrowser** [comment]
To get early objects

      # We compile 50 seconds maximum and then we interrupt
      - name: Compiling source-code
        working-directory: /mnt/storage/src
        run: timeout 50 ninja -C $GITHUB_WORKSPACE/out/android_arm chrome_public_apk || [ $? -eq 124 ]
