### ISSUE TITLE
[Question] manifest v3

### ISSUE THREAD

**Issue by baraa272** [kiwibrowser/src#200]
as edge chromium somewhat embraced the new API (manifest v3) , is there any sights of google pushing this change to mobile branch of chromium ? and those changes being pushed in kiwi ? , breaking the vast majority of ad blockers ?
also is there a difference between PC chromium branch and mobile branch ?

**Comment by kiwibrowser** [comment]
Kiwi is ManifestV2 only, I was strongly against ManifestV3, but I'm curious what users think ?

Is ManifestV3 enough to cover Adblock scenarios or it makes really too many good extensions disappear ?

If there is a possibility to not have to maintain anything extra, then I guess it'd be great

**Comment by baraa272** [comment]
Manifest 3 is a catastrophe upon vast majority of extensions overall 
The thing not only adblockers will be limited but many extensions will break completely

**Comment by kiwibrowser** [comment]
The main issue is that extensions maintainers themselves may lose motivation. I don't think the issue is that much technical (to keep extra APIs) :/

**Comment by LifeIsStrange** [comment]
Supporting manifest v3 is necessary and does not preclude dropping support for v2, manifest v2 will be supported for the years to come
