### ISSUE TITLE
Is it possible for you to make another kiwi  without extensions but with chromium up to date plus adblocking and tracking blocking capabilities & night mode & remove amp feature?

### ISSUE THREAD

**Issue by Sujan319** [kiwibrowser/src#202]
Kiwi2 without extensions but with adblocking(includes custom list or directly parse from url) & tracking blocking,night mode & other privacy features.

**Comment by irwan-batra** [comment]
there's already ungoogled chromium,or bromide or vanadium named browser.try that .they are open source

**Comment by ProjectX666** [comment]
Kiwi without extensions is meaningless.
Extensions and Webview update,both are what I want.
