### ISSUE TITLE
unable to save shortcuts on ntp

### ISSUE THREAD

**Issue by irwan-batra** [kiwibrowser/src#203]
![IMG_20201018_115129.jpg](https://user-images.githubusercontent.com/71307896/96360231-d556ac00-1138-11eb-977e-7d52a3230120.jpg)

**Comment by irwan-batra** [comment]
Problem persistent in current release.

I found Kiwi:flags also redirect to kiwi://flags
Could be recent update. Not sure though but its saves typing labor.

Arnoad sir if there anyway to make tiles of these path on ntp then let me know pls

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
