### ISSUE TITLE
Translate does not work when selecting google

### ISSUE THREAD

**Issue by rancidfrog** [kiwibrowser/src#205]
Google translate does not seem to work at all.
When selected as option in settings, clicking translate from menu opens google translate it shows original text.
Also, when going to translate.google.com and opening a site from it also only shows only original text.
Other browsers work fine.

**Comment by kiwibrowser** [comment]
Investigating it

**Comment by irwan-batra** [comment]
include link when you submit bug .

most site which needs cookies or signing face those kind of issues.

**Comment by kiwibrowser** [comment]
I managed to reproduce on Wikipedia

**Comment by kiwibrowser** [comment]
Fixed @ https://github.com/kiwibrowser/src/commit/1ef373e5a8d93cf5fbdbb54939ce0253e5aca527

**Comment by rancidfrog** [comment]
Great.

And, I did not post a link because it was an issue on multiple sites

**Comment by rancidfrog** [comment]
Confirmed working on Kiwi-323471841-arm64-signed.apk
Thank you for looking into this.

**Comment by kiwibrowser** [comment]
Thank you for taking the time to confirm that the issue has been resolved 👍
