### ISSUE TITLE
Swipe down/up for tab switcher not working

### ISSUE THREAD

**Issue by K1DV5** [kiwibrowser/src#206]
I'm using the browser on a Galaxy J4 core, which runs Android 8.1 go. And I can't get the tab switcher by swiping up or down on the address bar. I have enabled the feature in the accessibility settings. I checked on a Galaxy S3, running a custom Android 7, and it works flawlessly, so I think it is the OS or the hardware that makes the difference.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
