### ISSUE TITLE
White flash while opening screen in dark mode

### ISSUE THREAD

**Issue by kiwibrowser** [kiwibrowser/src#21]
Reported via e-mail:
"kiwi opening animation"

Sun, Apr 19, 2020 at 5:48 AM (Delivered after -259 seconds)
--

Love the app its almost perfect browser, but can you do something about the white screen that flashes as it loads up,its really annoying when using in the dark and everything on the phone is in the dark mode already.

**Comment by d3ward** [comment]
That seems to be fixed in latest builds 
Feel free to open an issue on [src.next](https://github.com/kiwibrowser/src.next) if bug persist
