### ISSUE TITLE
Will kiwi browser be affected when google enforce Manifest V3 

### ISSUE THREAD

**Issue by cpuuntery** [kiwibrowser/src#213]
The current state of Manifest V3 according to this [link](https://developer.chrome.com/extensions/migrating_to_manifest_v3) is the following
```
MV3 Stable Release: 2020
MV2 End of Life: To Be Determined
```
One of the reasons that made me install kiwi browser is to block ads using uBlock Origin. And I am sure that I am not the only one. And I think that 70% of people that installed kiwi browser also installed uBlock Origin. So what will kiwi browser developers do when google enforce Manifest V3

**Comment by kiwibrowser** [comment]
No Kiwi will keep the extension compatible.

**Comment by cpuuntery** [comment]
@kiwibrowser 
It is not about if uBlock Origin is compatible or not. It is about it being nerfed or not. if google enforce Manifest V3 you will still be able to install uBlock Origin but it will be less effective. And that is what my question is about

**Comment by kiwibrowser** [comment]
Yes Manifest V2 will stay :)

**Comment by kiwibrowser** [comment]
I answered it about a year ago on the Nano Adblocker issue tracker as well (where there is the uBlock Origin developer too I think)
