### ISSUE TITLE
browser closing by itself

### ISSUE THREAD

**Issue by hovnonium** [kiwibrowser/src#214]
My browser started automaticaly closing itself after last tab is closed, but that option in setting had never been activated.
Im using latest github version. No extensions.

**Comment by hovnonium** [comment]
Tried verions from play store, several reinstalations.
Happens on every build since yesterday, happened out of the blue. It has been working for few months without issues.

**Comment by irwan-batra** [comment]
i can help if you include video

**Comment by d3ward** [comment]
Do you still face the issue with recent update ? @hovnonium

**Comment by Oranko** [comment]
Fixed in the latest version
