### ISSUE TITLE
Allow to select multiple cookies to delete manually 

### ISSUE THREAD

**Issue by irwan-batra** [kiwibrowser/src#216]
![Screenshot_2020-10-23-05-33-29-535_com.craiovadata.applicationhidestatus.jpg](https://user-images.githubusercontent.com/71307896/96942344-802ce880-14f2-11eb-9fd0-60ca5b2e28cd.jpg)

**Comment by KaKi87** [comment]
This site list and its search feature is about browsing site settings in general, not cookies settings specifically.
Additionally, those settings allow deleting all website data, but not only cookies.
However, you can delete cookies without deleting other data when visiting the website and clicking the address bar icon.
What you can eventually ask for is being able to clear all data of multiple websites from site list & search results.
Feel free to open further issues at [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
