### ISSUE TITLE
session box extension broke on current release release

### ISSUE THREAD

**Issue by irwan-batra** [kiwibrowser/src#217]
https://chrome.google.com/webstore/detail/sessionbox-free-multi-log/megbklhjamjbcafknkgmokldgolkdfig

![Screenshot_2020-10-23-05-57-00-498_com.kiwibrowser.browser.jpg](https://user-images.githubusercontent.com/71307896/96943800-c7b57380-14f6-11eb-98b6-f92d3c71267e.jpg)

it never shows green indication

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
