### ISSUE TITLE
Fullscreen video not working in Samsung Dex

### ISSUE THREAD

**Issue by Awangatangg** [kiwibrowser/src#218]
I've been running into issues with Kiwi browser when watching video in Samsung Dex. Everything runs fine until I try to make the video fullscreen, which always ends up breaking the video and giving me some kind of error. This has happened no matter what website i've tried whether its youtube, espn, netflix, etc.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
