### ISSUE TITLE
Unable to use whatsapp web on kiwi browser android

### ISSUE THREAD

**Issue by vyeshwanth** [kiwibrowser/src#219]
I'm seeing the below error message when trying to use whatsapp web. whastapp web works completely fine on chrome. 

Sorry, something went wrong.
We're working on getting this fixed as soon as we can

Below is the device information
Device: samsung galaxy tab s7
Kiwi version: Git201022
Android version: 10
![Screenshot_20201024-135422_Kiwi Browser](https://user-images.githubusercontent.com/16932584/97077357-b22c7080-1600-11eb-941b-b1f3926177b7.jpg)

**Comment by rajipeter** [comment]
this problem is still not solved . please solve this bug. 
![kiwi](https://user-images.githubusercontent.com/87066423/124734707-40fcc700-deca-11eb-8c81-3d84aee33c9e.jpg)

**Comment by rajipeter** [comment]
dear vyeswanth i am on +919019553446

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
