### ISSUE TITLE
Please support android tv

### ISSUE THREAD

**Issue by qw123wh** [kiwibrowser/src#22]
Can you create a version of kiwi browser with support for extensions also for android tv?

**Comment by sorryusernameisalreadytaken** [comment]
Absoltely thumbs up for that.

At the moment I use Firefox for FireTV apk but sadly the developmemt is in slow motion.
I really hope for a better Android TV browser apk with dpad support

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
