### ISSUE TITLE
Download Notification Hangs Upon Completion

### ISSUE THREAD

**Issue by allanrps** [kiwibrowser/src#221]
This issue arose after the last update, and happens on about 1/3 of downloads. The status bar for the download will reach approx 99% and then the status will not be updated, even while the download has completed. Both the notification and download page of kiwi browser reflect the froze status,, and trying to pause the download has no result. The status notification persists until kiwi browser is forcefully stopped. Proper functionality wouod have the status reach 100% and the notification be dismissed and replaced with a download complete notification.

**Comment by KaKi87** [comment]
Covered by kiwibrowser/src.next#151
