### ISSUE TITLE
Full Screen Media Content Not Displaying Properly

### ISSUE THREAD

**Issue by allanrps** [kiwibrowser/src#222]
My device is a Samsung Galaxy Note 10+ on Android 10. This problem has persistes since I first got the device. Full screen media content does not fill the bottom 200px or so of the screen, causing the webpage to show in that area while the content is shrunken. Touch inputs are not registered on the area where the video is not displayed while in full screen mode. This is the case for all full screen video content. For YouTube, it appears to be the top 200px or so that is not displayed. I have included some screenshots showing the issue.

![Screenshot_20201026-064159_Kiwi Browser](https://user-images.githubusercontent.com/50152765/97163348-6d2b4a00-1778-11eb-90bc-70b867178056.jpg)
![Screenshot_20201026-064139_Kiwi Browser](https://user-images.githubusercontent.com/50152765/97163354-6e5c7700-1778-11eb-9c6b-6c1aa0fcf741.jpg)
![Screenshot_20201026-064056_Kiwi Browser](https://user-images.githubusercontent.com/50152765/97163358-6ef50d80-1778-11eb-9142-0bfd084ab7f3.jpg)

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
