### ISSUE TITLE
Search results on Wikipedia are not clickable

### ISSUE THREAD

**Issue by ksio89** [kiwibrowser/src#224]
When you search anything on Wikipedia (https://en.m.wikipedia.org/w/index.php?search=), none of the results open when "clicked" on. It also happens on desktop version. For what is worth, if you click the Search button, a page with article previews will be loaded, and all these links open normally. 

I'm using the latest build (arm64 signed 330268858).

![Screenshot_20201028-152157](https://user-images.githubusercontent.com/30641861/97480820-b45d3a80-1932-11eb-9fff-194ded201490.png)

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
