### ISSUE TITLE
"Block User" button on Disqus does not work

### ISSUE THREAD

**Issue by ksio89** [kiwibrowser/src#225]
On websites that have Disqus commenting system implemented, the **Block User** button shown by clicking the arrow doesn't respond, unlike the **Flag as inappropriate** one. 

Actually, in the page featured in the screenshot it does work, but I just used it to illustrate the bug as it happens in all other sites that employ Disqus platform.

![Screenshot_20201028-194605](https://user-images.githubusercontent.com/30641861/97506046-d79ae080-1958-11eb-9998-223c1615c282.png)

**Comment by csehszlovakze** [comment]
Can confirm. The workaround is to go to the user's page and block them there.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
