### ISSUE TITLE
Browser hangs when trying to clear browsing data

### ISSUE THREAD

**Issue by rancidfrog** [kiwibrowser/src#229]
App hangs on,
![](https://i.imgur.com/DlOdq8B.jpg)

Nothing seems to be happening.
In all other browser apps clearing data takes seconds

**Comment by kiwibrowser** [comment]
I'm not sure how to reproduce this one :(
I have no clue what is the trigger for that but I saw it once (unfortunately, the next time it worked).

I suspect it's a bug upstream in Chromium as I had issue with Chrome too

**Comment by rancidfrog** [comment]
I do not know exactly.
But, every time I have tried to clear everything ?but history, it seems to hang.
I just tried again, this time changing time range to _All time_ and same thing - Please wait... circle of death

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
