### ISSUE TITLE
Facebook redirects to the mobile site even when Desktop mode is enabled

### ISSUE THREAD

**Issue by michallepicki** [kiwibrowser/src#23]
When desktop mode is enabled and user navigates to `www.facebook.com`, the full desktop website should be opened.

I am not sure what kind of browser detection magic Facebook is doing. Possibly just slightly tweaking user agent header in Desktop mode could help.

**Comment by kiwibrowser** [comment]
Related code: https://github.com/kiwibrowser/src/blob/b1ea3ea95d8ac15fc0b49acd83ba2f8b1aaa8d2b/net/url_request/url_request_http_job.cc#L451

The reason behind that was to force-enable Facebook Messenger. Otherwise Facebook forces you to install their Messenger app

**Comment by michallepicki** [comment]
I think it doesn't do that in the desktop version of the site? At least in Samsung Internet, in Desktop mode, the full Facebook webpage's messages popups work fine

**Comment by kiwibrowser** [comment]
Maybe they changed it with recent versions of Facebook ?
I think the lines can be removed.

This may take about a day as I am setting up the new build environment directly in GitHub Actions here.
This will automatically take pull requests and build an APK that we can test

**Comment by michallepicki** [comment]
I think the linked lines are useful to be applied when using the mobile website, but when browser Desktop mode is enabled, the "linux chromium" user agent header sent in this mode should work good enough. So possibly the linked line needs to check whether desktop mode is enabled or not?

aside:
> I am setting up the new build environment directly in GitHub Actions here

I am curious to see if free GitHub Actions will handle the weight of Chromium compilation :D

**Comment by kiwibrowser** [comment]
Done
