### ISSUE TITLE
[Question] Old chromium version

### ISSUE THREAD

**Issue by aliglelo** [kiwibrowser/src#231]
The base for latest playstore version of KIWI browser is Chromium 77.SO my question is why KIWI is lacking behind by so many version form latest chromium stable releases?

**Comment by kiwibrowser** [comment]
Only the UI is 77-based (mostly), other parts are way more recent.
The goal is not to copy Chromium updates but to make its own choices

**Comment by csehszlovakze** [comment]
@kiwibrowser is this CVE fixed in the current version?

https://www.theregister.com/2020/11/04/google_chrome_critical_updates/

**Comment by kiwibrowser** [comment]
Yes, see latest commits
