### ISSUE TITLE
Enable lazy image loading

### ISSUE THREAD

**Issue by yeezylife** [kiwibrowser/src#232]
I think this could be a very useful setting for mobile users,but when you open kiwi://flags,there's only"Enable lazy frame loading".
Why doesn't Kiwi support“Enable lazy image loading” like chrome did.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
