### ISSUE TITLE
Missing "undo" after closing tab

### ISSUE THREAD

**Issue by hovnonium** [kiwibrowser/src#234]
Hello, there is missing 'undo' button when any tab is removed.  Im on latest googleplay store version but its missing since first github version, happens in english and also czech languange.
![IMG_20201107_094447](https://user-images.githubusercontent.com/58630211/98436752-350ff980-20de-11eb-8058-d44a806a5bab.jpg)

However, i can still tap on that region to brinf back closed tab.

**Comment by Oranko** [comment]
Fixed in the latest version.
