### ISSUE TITLE
Simulate updated Chromium with flags

### ISSUE THREAD

**Issue by Madis0** [kiwibrowser/src#235]
I recommend enabling the following flags for everyone to make it at least seem like the Chromium version is internally updated: 

<details>

Clear older browsing data
Enables clearing of browsing data which is older than a given time period. – Android

#clear-old-browsing-data

Enable new Photopicker
Activates the new picker for selecting photos. – Android

#enable-new-photo-picker

Fast tab/window close
Enables fast tab/window closing - runs a tab's onunload js handler independently of the GUI. – Mac, Windows, Linux, Chrome OS, Android

#enable-fast-unload

Password generation
Allow the user to have Chrome generate passwords when it detects account creation pages. – Mac, Windows, Linux, Chrome OS, Android

#enable-password-generation

Reduce default 'referer' header granularity.
If a page hasn't set an explicit referrer policy, setting this flag will reduce the amount of information in the 'referer' header for cross-origin requests. – Mac, Windows, Linux, Chrome OS, Android

#reduced-referrer-granularity

Strict site isolation
Security mode that enables site isolation for all sites. When enabled, each renderer process will contain pages from at most one site, using out-of-process iframes when needed. When enabled, this flag forces the strictest site isolation mode (SitePerProcess). When disabled, the site isolation mode will be determined by enterprise policy or field trial. – Mac, Windows, Linux, Chrome OS, Android

#enable-site-per-process

Optimize background video playback.
Disable video tracks when the video is played in the background to optimize performance. – Mac, Windows, Linux, Chrome OS, Android

#disable-background-video-track

Rotate-to-fullscreen gesture for videos.
Enter/exit fullscreen when device is rotated to/from the orientation of the video. Only on phones. – Android

#video-rotate-to-fullscreen

Enable custom context menu
Enables a new context menu when a link, image, or video is pressed within Chrome. – Android

#enable-custom-context-menu

Omnibox clipboard URL suggestions
Provide a suggestion of the URL stored in the clipboard (if any) upon focus in the omnibox. – Android

#enable-clipboard-provider

Omnibox UI Elide Suggestion URL After Host
Elides the path, query, and ref of suggested URLs in the Omnibox dropdown. – Mac, Windows, Linux, Chrome OS, Android

#omnibox-ui-elide-suggestion-url-after-host

Omnibox UI Hide Steady-State URL Scheme and Trivial Subdomains
In the Omnibox, hide the scheme and trivial subdomains from steady state displayed URLs. Hidden portions are restored during editing. For Mac, this flag will have no effect unless MacViews is enabled. – Mac, Windows, Linux, Chrome OS, Android

#omnibox-ui-hide-steady-state-url-scheme-and-subdomains

Parallel downloading
Enable parallel downloading to accelerate download speed. – Mac, Windows, Linux, Chrome OS, Android

#enable-parallel-downloading

Enable download progress infobar
Enables an infobar notifying users about status of current downloads. – Android

#download-progress-infobar

New Media Controls
Enables the new style native media controls. – Mac, Windows, Linux, Chrome OS, Android

#enable-modern-media-controls

Mark non-secure origins as non-secure
Change the UI treatment for HTTP pages – Mac, Windows, Linux, Chrome OS, Android

#enable-mark-http-as

Query in Omnibox
Only display query terms in the omnibox when viewing a search results page. – Android

#enable-query-in-omnibox

Block unsafe downloads over insecure connections
Disallows downloads of unsafe files (files that can potentially execute code), where the final download origin or any origin in the redirect chain is insecure. – Mac, Windows, Linux, Chrome OS, Android

#disallow-unsafe-http-downloads

</details>

**Comment by Oranko** [comment]
Browser has now been updated to latest chromium
