### ISSUE TITLE
In night mode pre-dark buttons are not visible

### ISSUE THREAD

**Issue by Cyberavater** [kiwibrowser/src#236]
![Screenshot_20201018-152700948](https://user-images.githubusercontent.com/32187927/98495707-03c43480-226a-11eb-9d8e-1ced100f40d8.jpg)
![Screenshot_20201018-152730010](https://user-images.githubusercontent.com/32187927/98495711-06268e80-226a-11eb-97aa-0303f659a928.jpg)

You can see the reload button by re-captcha is not visible in night mode.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
