### ISSUE TITLE
Allow copy of image url on long-press

### ISSUE THREAD

**Issue by rancidfrog** [kiwibrowser/src#239]
Long-pressing images do not allow to copy address of image

![](https://i.imgur.com/AgBrwNF.jpg)

Share does not include 'copy',
 either.
![](https://i.imgur.com/PArMuK0.jpg)

For context:
![](https://i.imgur.com/4BGtJdM.jpg)

Copy image URL is useful, as the only other workaround is to
1. long-press
1. Open image in new tab
1. click on adress bar and manually copy url

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
All that is included
