### ISSUE TITLE
[BUG] NoScript: Delay in Loading the Configuration Page

### ISSUE THREAD

**Issue by CosmicPegasis** [kiwibrowser/src#243]
## Introduction
I downloaded Kiwi a few days ago and have been testing all the major extensions such as uBlock Origin, Privacy Badger.

## The Issue With NoScript
Even the NoScript Security Suite is working as expected but the problem is the extension configuration page i.e. the page where you can select which domains to allow scripts from for every website you visit, takes a long time to become interactable.

### In Depth
The peculiar thing I noticed was that the NoScript UI loaded up completely but none of the elements were interactable, along with this the site names for which we can manage settings didn't show up at first, when I waited on the page for about 30 seconds though, everything started working as it should, the domain names loaded up, the buttons became interactable etc.  

This leads me to believe this might just be a performance issue.

#### Conclusion
This issue was above, I just want to thank the developer(s) for taking the time, this browser is amazing and I've already decided to use this as a daily driver. I would love to contribute to this project in some way but neither do I have the money nor the programming expertise(at least not right now) however if there is any other way I can help the devs, I would be really really be happy to!

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
