### ISSUE TITLE
Home screen option doesn't work

### ISSUE THREAD

**Issue by mindplay-dk** [kiwibrowser/src#244]
I've set the "Home Page" option to "Off" in the settings.

It seems every new tab open the same landing page, regardless of this setting.

I've also tried restarting the browser, that didn't help.

(On that note, it would be nice if opening a new tab would also focus the address bar, so you don't have to tap twice every time you open a new tab.)

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
