### ISSUE TITLE
Error: Cannot set property 'location' of null     with    hypothes login form

### ISSUE THREAD

**Issue by redstoneleo** [kiwibrowser/src#245]
Procedure to reproduce the exception :

1. Open https://via.hypothes.is/https://en.m.wikipedia.org/wiki/Occam%27s_razor
2. Select any word on the page
3. Tap the Annotation action in the pop-up menu, the you will see the hypothes login form, click the login in  link , then you would see the exception 

![image](https://user-images.githubusercontent.com/5896180/99567789-8dfa5e80-2a09-11eb-98e2-75c40674abd6.png)

So how to solve it ?

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
