### ISSUE TITLE
2 extensions have some errors

### ISSUE THREAD

**Issue by leoxxx** [kiwibrowser/src#246]
Tampermonkey 4.11
https://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo
error: can't delete & reset script.

User-Agent Switcher v2.5.0
https://chrome.google.com/webstore/detail/aedikcfpfonanffanecfolneiaoakmlc
error: can't remove group & UA.

**Comment by iseeyo** [comment]
The problem still exists!

**Comment by leoxxx** [comment]
Still error in 570536402

**Comment by leoxxx** [comment]
Great! It's fixed in 93.0.4577.9.
