### ISSUE TITLE
fails to run React App created with Chrome/Chromium Browser target

### ISSUE THREAD

**Issue by TheDiveO** [kiwibrowser/src#248]
- Kiwi Android App, Git201105Gen347353974, freshly installed from Android Market.
- React 16.13.1 and using create-react-app.
- excerpt from package.json related to the webpack-generated Javascript code; it targets the current Chrome version: 
  ```json
  "browserslist": {
    "development": [
      "last 1 chrome version",
    ]
  }
  ```
- `yarn start` and then navigating to the development server's IP and port on the Android device in Kiwi.

While this react (development) app works correctly on Chrome on Windows, as well as Chromium on Linux and Chrome on Android, the app fails in Kiwi due to missing support for `Array.flat`.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
