### ISSUE TITLE
Desktop OS builds?

### ISSUE THREAD

**Issue by mindplay-dk** [kiwibrowser/src#249]
Any plans for Windows/MacOS/Linux desktop builds?

(I recently got fed up with Chrome for various reasons and started using Kiwi first on mobile, then on my tablet. Better performance and fewer ads, yes please! Would love to have Kiwi on my Windows computer - with devtools, which seems to be planned anyhow... Having to use regular Chrome in such a drag now.)

**Comment by Madis0** [comment]
Probably unlikely, but there are already many privacy-friendly Chromium browsers: Brave, Vivaldi, Iridum, Iron, Epic...

**Comment by csehszlovakze** [comment]
For linux you might wanna try vanilla Chromium to see if it's better, but I'm also a Vivaldi fan for desktop.

**Comment by mindplay-dk** [comment]
I'm actually on Vivaldi now, somewhat reluctantly.

I found too many sites that have bugs (or don't work at all) because Kiwi doesn't (yet?) follow Chromium releases. I don't know how far Kiwi is behind Chromium, but far enough that it's becoming a problem. (I really like Kiwi, but it's a bit like running an outdated browser with a modern shell - so I probably won't use it again before it's running a more up-to-date browser core.)

Anyhow, following Chromium probably ought to have higher priority than a desktop version.

**Comment by Oranko** [comment]
Hey, kiwi has now been updated to the latest chromium. Also the developer has no plans on releasing a desktop browser.
