### ISSUE TITLE
desktop mode by default cannot work

### ISSUE THREAD

**Issue by kuonji-arisu** [kiwibrowser/src#250]
Application Version: Git201105
Device: Lenovo TB-J760F Tab P11 Pro
Test Website: bilibili.com   imomoe.ai

I have turned on the option of default desktop mode.
But when I open the above webpage and randomly enter a link in those webpages, it will still automatically jump to the mobile version.
But I don’t have this situation with Samsung browser.(turn on force desktop mode option)

**Comment by d3ward** [comment]
Issue moved to [src.next/issues/62](https://github.com/kiwibrowser/src.next/issues/62 )
