### ISSUE TITLE
Crash of Kiwi-347353974-arm-signed.apk on moto e5 play, API Level 27 device

### ISSUE THREAD

**Issue by aperets** [kiwibrowser/src#253]
Build fingerprint: 'motorola/pettyl/pettyl:8.1.0/OPG28.54-53-8/55beb:user/release-keys'
Revision: 'p300'
ABI: 'arm'
pid: 12027, tid: 12134, name: Thread-2 >>> com.kiwibrowser.browser <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'Cannot get a dirty matrix!'
r0 00000000 r1 00002f66 r2 00000006 r3 00000008
r4 00002efb r5 00002f66 r6 944ed1c4 r7 0000010c
r8 00000000 r9 a419ce00 sl 1360d908 fp 12d90dd8
ip 13635338 sp 944ed1b0 lr adf82981 pc adf7c46e cpsr 20070030

The full log is here:
https://drive.google.com/file/d/1neGSTk2qQRhesAuQl6dvUFrPGWT34d3q/view?usp=sharing

**Comment by d3ward** [comment]
Thanks for the multiple logs you provided . 
Now you can check out latest Kiwi builds  on [src.next](https://github.com/kiwibrowser/src.next)
