### ISSUE TITLE
The browser won't start. Kiwi-347353974-arm-signed.apk on Nexus 6P, Virtual, API Level 27 device

### ISSUE THREAD

**Issue by aperets** [kiwibrowser/src#254]
The log is here:
https://drive.google.com/file/d/1ED6E8Mjzv_Qni3NO1JW9geytHjn63JHR/view?usp=sharing

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
