### ISSUE TITLE
Crash of Kiwi-347353974-arm-signed.apk on H8324 device

### ISSUE THREAD

**Issue by aperets** [kiwibrowser/src#258]
Build fingerprint: 'Sony/H8324/H8324:8.0.0/51.1.A.11.51/618810433:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 21785, tid: 22055, name: RenderThread >>> com.kiwibrowser.browser <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'GL errors! frameworks/base/libs/hwui/renderthread/OpenGLPipeline.cpp:105'
r0 00000000 r1 00005627 r2 00000006 r3 00000008
r4 00005519 r5 00005627 r6 cf8ba340 r7 0000010c
r8 cf8ba7d8 r9 cf8ba7e8 sl cf8ba7d8 fp 05d8cd90
ip 00000000 sp cf8ba330 lr f31a571f pc f31d5cc8 cpsr 200f0010
backtrace:
#00 pc 0004acc8 /system/lib/libc.so (tgkill+12)
#1 pc 0001a71b /system/lib/libc.so (abort+54)
#2 pc 00006699 /system/lib/liblog.so (__android_log_assert+152)
#3 pc 00036e35 /system/lib/libhwui.so (_ZN7android10uirenderer12renderthread14OpenGLPipeline11swapBuffersERKNS1_5FrameEbRK6SkRectPNS0_9FrameInfoEPb+116)
#4 pc 000353e1 /system/lib/libhwui.so (_ZN7android10uirenderer12renderthread13CanvasContext4drawEv+208)
#5 pc 0003794b /system/lib/libhwui.so (_ZN7android10uirenderer12renderthread13DrawFrameTask3runEv+142)
#6 pc 0003c2cf /system/lib/libhwui.so (_ZN7android10uirenderer12renderthread12RenderThread10threadLoopEv+166)
#7 pc 0000d4f9 /system/lib/libutils.so (_ZN7android6Thread11_threadLoopEPv+140)
#8 pc 00079a09 /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+80)
#9 pc 00047fdf /system/lib/libc.so (_ZL15__pthread_startPv+22)
#10 pc 0001b2c5 /system/lib/libc.so (__start_thread+32)

The full log is here:
https://drive.google.com/file/d/1QOkxhUO3kOVSexvYrKyl90ZwYfDd_4Yf/view?usp=sharing

**Comment by Oranko** [comment]
Hey, can you try the latest version?
