### ISSUE TITLE
cname cloaking blocker

### ISSUE THREAD

**Issue by ghost** [kiwibrowser/src#259]
Brave browser and ublock origin already have this
https://github.com/gorhill/uBlock/releases/tag/1.25.0
brave/brave-core#6640

cname cloaking is a serious issue, various third party disguise to be first party and hence are not blocked and collect data, i would like to have cname cloaking blocker in kiwi

**Comment by d3ward** [comment]
Check out latest Kiwi builds  on [src.next](https://github.com/kiwibrowser/src.next)
