### ISSUE TITLE
Modifying more icon images

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [kiwibrowser/src#261]
Seen from your package on X-plore app, I think you should modify rest of icons to adopt your logo. They are app_shortcut_icon.png, app_single_page_icon.png.

![Screenshot_20201207-191742](https://user-images.githubusercontent.com/10364351/101370668-be386d00-38e4-11eb-9f8c-49f00a2a9dc5.png)

**Comment by KaKi87** [comment]
Fixed in kiwibrowser/src.next@ce20ee7
