### ISSUE TITLE
Unsupported browser on element.io

### ISSUE THREAD

**Issue by laem** [kiwibrowser/src#262]
There seems to be a JS / other missing element in Kiwi to access https://element.io

More info here https://github.com/vector-im/element-web/issues/15928

**Comment by laem** [comment]
Update : unchecking the integrated adblocker lets me access the app, but fails to show the rooms sidebar.





![Screenshot_20201208-135424_Kiwi Browser](https://user-images.githubusercontent.com/1177762/101486431-eebbed80-395c-11eb-9c54-fdbd25f302cc.jpg)

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
