### ISSUE TITLE
Disabling edge swipe keeps me from taking screenshots

### ISSUE THREAD

**Issue by nullbasis** [kiwibrowser/src#266]
I (usually) have edge swipe disabled in Kiwi.

However, on my phone (Samsung Galaxy A20) the default motion for taking a screenshot is swiping left or right across the screen with the edge of your palm. As I discovered just now, this behavior is disabled when I have edge swipe turned off. Turning edge swipe back on fixes the problem.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
