### ISSUE TITLE
Night mode makes some text-entry boxes unreadable

### ISSUE THREAD

**Issue by nullbasis** [kiwibrowser/src#267]
...but only some of them.

In _some_ places where I encounter textarea boxes, night mode turns the text color white as expected but leaves the box white also instead of turning it black. In other places, the text box is turned black as it should be.

The bug only seems to happen when there's no CSS rule in effect for the color of the box or the text inside of it. I made a quick and dirty little page here to demonstrate the bug: https://nullbasis.github.io/index.html

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
