### ISSUE TITLE
Narrower tab-bar & address-bar

### ISSUE THREAD

**Issue by zuelwyw** [kiwibrowser/src#268]
When I use kiwi on my Huawei matepad 10.8, desktop mode, the tab-bar & address-bar look like this:
![Screenshot_20201216-142330](https://user-images.githubusercontent.com/57886684/102312775-f23f0e00-3f34-11eb-8d3d-0724370ad006.jpg)
It may be too wide, so I'm wondering if you can make it narrower, like this picture?
![Screenshot_20201216-143036](https://user-images.githubusercontent.com/57886684/102313272-f15aac00-3f35-11eb-83e1-bc4e3ac2b7b3.jpg)
The browser in the second picture is called "stardust browser", provided by phoenix os team:[http://www.phoenixos.com/browser/intro-pad](url).
Although such a narrow bar may be difficult to make, I hope you can just try to make it come true.

**Comment by d3ward** [comment]
That's not possible .
Anyway you can check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
