### ISSUE TITLE
Anti-adblock screen message

### ISSUE THREAD

**Issue by ihackurmind** [kiwibrowser/src#269]
![Screenshot_20201216-084206](https://user-images.githubusercontent.com/25226744/102319445-2dfcc680-3f7b-11eb-977c-051eea98ea70.png)

Hello little kiwis 
An Anti-adblock screen message started showing on some pages. 
I use ad-block. Is there anyway to get rid of it? 
What about making the adblock feature integrated into kiwi? :) 
Thank you

**Comment by CEHitchens** [comment]
Have you tested the uBlock Origin extension?
I just accessed repubblica.it with Kiwi and that extension - and tbh quite a few blocking/filtering lists enabled - and I don't see any such banner.

**Comment by ihackurmind** [comment]
> Have you tested the uBlock Origin extension?
> I just accessed repubblica.it with Kiwi and that extension - and tbh quite a few blocking/filtering lists enabled - and I don't see any such banner.

Thanks! <3 installed uBlock Origin and it solved the issue. Hope I will not get troubles on other websites!
