### ISSUE TITLE
On tablet: missing ability to move tab&address bar to bottom of screen

### ISSUE THREAD

**Issue by CEHitchens** [kiwibrowser/src#270]
It is nice to have those user interface bars at the bottom of the screen on phone devices, incl. the autohide feature.

Unfortunately on tablets the option to have those shown/appear at the bottom of the screen is not available. 

Since tablet displays are bigger than phone displays, the distance to cover with one's fingers to reach the top of the screen (and the keyboard being at the bottom of it) is bigger than on phones, so I'd argue that it'd make at least as much sense on tablets as on phones.

P.S.: I am genuinely impressed by your Kiwi browser! And being able to add uBlock Origin makes up for the "block _some_ ads". Two thumbs up!

/edit: typos

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
