### ISSUE TITLE
Add functionality to scroll to the top and end of web pages

### ISSUE THREAD

**Issue by alleluia20** [kiwibrowser/src#271]
Hello,

There are still plenty of web pages that are long, even pages designed for mobile devices. In those cases, scrolling to the top or end of the page can take time and effort. I know there are some Chrome extensions that add buttons to scroll to the top and to the end, but those extensions have few downloads, so I would not have peace of mind regarding their security.

I therefore propose that Kiwi gives the option to scroll to the top and to the end, out of the box. One possibility would be to implement something similar to what Opera for Android has: when you scroll up (down), the scrollbar on the right is actually a button to scroll to the top (end). Other approaches would also be fine: for example, a button to scroll to the top (end) that displays when one scrolls up (down).

Regards.

**Comment by d3ward** [comment]
I don't think this will be implemented .
A good solution can be using that extension https://github.com/d3ward/floatly , it  have a nice shortcut( floating button) with multiple actions including scroll to top or to bottom 
Feel free to reopen the issue if needed
