### ISSUE TITLE
Keeps on displaying Google's cookies dialogue

### ISSUE THREAD

**Issue by alleluia20** [kiwibrowser/src#272]
Hello,

I have the option "accept cookies" checked in. While many cookies warnings do not display any more, several still do: as an example, the cookies dialogue from Google. When I open a private tab and do a search (with Google), I get the "before you continue" warning. If I then open Youtube on the same private tab, I get the warning again (a second time!).

Can Kiwi automatically accept this dialogue, as it does with other cookies warnings?

It would also be great to block the "sign in" popups on Youtube too, but I do not know whether I should open a separate issue for that. Otherwise, you may consider this too, please.

Regards.

**Comment by Oranko** [comment]
Hey, can you try ublock origin and from filter lists in annoyances check the Easy List cookie. That should work for most sites and if it doesn't you can use this reputed extension to remove cookies popup from all sites.
https://chrome.google.com/webstore/detail/i-dont-care-about-cookies/fihnjjcciajhdojfnbdddfaoknhalnja?hl=en
