### ISSUE TITLE
Microsoft authenticator / autofill addon support

### ISSUE THREAD

**Issue by sergioad** [kiwibrowser/src#273]
Hello friends, could you please add Microsoft Authenticator autofill support or fix the autofill extension to work on Kiwi? I really want to have native Android autofill support

**Comment by aravindkamaraj** [comment]
Please add support for autofill addon,it is the only reason I moved to other browsers.

**Comment by ItsCubeTime** [comment]
> Please add support for autofill addon,it is the only reason I moved to other browsers.

Is there even another browser that has addon support nowadays? Firefox used to until an update in 2020 where they deprecated it

**Comment by sergioad** [comment]
> Firefox used to until an update in 2020 where they deprecated it

They added them back

**Comment by d3ward** [comment]
[src.next#64](https://github.com/kiwibrowser/src.next/issues/64)

**Comment by aravindkamaraj** [comment]
I tried to use both bitwarden and dashlane but autofill option of neither  worked with kiwi browser but it works perfectly fine with other browsers like brave, chrome,firefox etc.
