### ISSUE TITLE
The problem of playing video on the web

### ISSUE THREAD

**Issue by jie-neng** [kiwibrowser/src#274]
When I was playing the video of Baidu disk（ https://pan.baidu.com/ ）"Can't connect to the network, please try again later", but I'm sure I'm connected to WiFi. What's going on? Browser I use bilibili.com No problem watching the video. Is it about two players? Flash and HTML5 problems?
当我在播放百度网盘的视频（https://pan.baidu.com/）的时候，提示“无法连接到网络，请稍后再试”，可是我确定我已经连上了wifi，这是怎么回事？浏览器我用bilibili.com看视频没问题啊。是两个播放器的问题？flash和html5的问题？

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
