### ISSUE TITLE
text reflow does not work, prevents scrolling when in use

### ISSUE THREAD

**Issue by bahbarnett** [kiwibrowser/src#276]
When I zoom in on a web page, with text reflow in play, more often than not, everything breaks.

- when zoomed in, some elements are enlarged (pics, etc), and therefore are off, or partially off screen.  you have to fight with the browser to get it to scroll right, with it actively flying back to the left as you scroll right, only succeeding after many attempts
- some pages have large tables, which always remain partially off screen, and are impossible scroll to (see above)
- when zooomed in, the slightest move of your finger often sends the page flying away, scroll 10x, or even 50x as much as you move your finger

You can see much of this behaviour, by turning on text reflow, and then going to any page which is designed so that, once you zoom, elements of it remain off page.  Simply zoom in until something is off-screen, and try to scroll right.

In terms of accelerated finger movement response, zoom in a lot, and you will see that the slightest movement sends the page flying all over the place.

Currently, text-reflow is unusable.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
