### ISSUE TITLE
MDN pages come up blank

### ISSUE THREAD

**Issue by mindplay-dk** [kiwibrowser/src#279]
All MDN pages seem to come up blank?

For example:

https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API

It kind of flashes in for a moment, if I reload the page, but then disappears.

**Comment by rururux** [comment]
That because kiwi does not support Array.prototype.flat().
This can be solved by putting this Polyfill into tampermonkey or something similar.
https://github.com/jonathantneal/array-flat-polyfill/blob/master/src/polyfill-flat.js

**Comment by mindplay-dk** [comment]
Why not supported?

Aren't you pulling changes from the Chromium project?

This feature is in all major browsers since more than two years. 🤔

**Comment by rururux** [comment]
i don't know. 🤷‍♂️
i'm not a developer/contributor of this.
but I found it this way:
`addEventListener("error", err => alert(err.message))`
![Screenshot_20210104-023239~02](https://user-images.githubusercontent.com/5568054/103485000-6edb5300-4e36-11eb-8439-5db3f4d04617.png)

**Comment by Flexmaen** [comment]
https://selbsttest.stmk.gv.at doesn't work either on Kiwi.

**Comment by Oranko** [comment]
Fixed in the latest update
