### ISSUE TITLE
Website loading progress bar is invisible when using bottom toolbar on Android 10

### ISSUE THREAD

**Issue by ghost** [kiwibrowser/src#28]
Steps to reproduce:
1. Open Kiwi Browser, set the browser to use bottom toolbar, go to a website
2. See the website loading progress bar being invisible.
3. If I click on the tabs icon and click it again it becomes visible but If I click on a link in the website or load another website it becomes invisible again.

Device: Motorola One Power, Android 10.
Kiwi Browser version: Quadea.

**Comment by marcusatiliusregulus** [comment]
cannot confirm, i do see it. android 10, kiwi: git200915
