### ISSUE TITLE
How can I delete the tampermonkey script?

### ISSUE THREAD

**Issue by iseeyo** [kiwibrowser/src#280]
Tampermonkey
https://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo
error: can't delete & reset script.

User-Agent Switcher
https://chrome.google.com/webstore/detail/aedikcfpfonanffanecfolneiaoakmlc
error: can't remove group & UA.

**Comment by Oranko** [comment]
Please try this in the latest version, I tried the tampermonkey issue and I'm able to delete the scripts with no problem. If you still have an issue we will glad to help you out in the kiwi discord server.
