### ISSUE TITLE
Dark search widget

### ISSUE THREAD

**Issue by MrFeelgoood** [kiwibrowser/src#281]
I really like Kiwi. Could you reshape the search widget to look like the address bar (smoothly rounded instead of rectangular) and darken it when night mode is on ?
Thank you for your work here.

**Comment by ItsCubeTime** [comment]
1 up for this

Doesnt quite fit in with any widgets that does support dark mode https://imgur.com/a/aZBAuyX

**Comment by Oranko** [comment]
Added in the latest update with the latest chromium

**Comment by ItsCubeTime** [comment]
![](https://media2.giphy.com/media/l3q2zVr6cu95nF6O4/giphy.gif)
