### ISSUE TITLE
Google OAuth flow fails for scope "openid email profile"

### ISSUE THREAD

**Issue by abaker** [kiwibrowser/src#282]
I'm not an expert on OAuth so I have no idea if this is a user error, but my Google OAuth flow appears to hang in Kiwi (tested with version Git201105Gen347353974)

* If the scope is "openid email profile", after selecting an account I get a spinner, and after a short time I am redirected to the Google home page ([demo apk](https://github.com/kiwibrowser/src/files/5748867/appauth-demoapp-debug-openid-email-profile.apk.zip))
    * This scope works in Chrome (87.0.4280.101) and Firefox
* If I add a scope, e.g. "openid email profile https://www.googleapis.com/auth/tasks", after selecting an account I get the consent screen, and can complete the OAuth flow successfully ([demo apk](https://github.com/kiwibrowser/src/files/5748865/appauth-demoapp-debug-openid-email-profile-tasks.apk.zip))

To reproduce this yourself with the [AppAuth-Android](https://github.com/openid/AppAuth-Android) demo app:
1. [Create Android credentials for Google Cloud](https://developers.google.com/identity/protocols/oauth2/native-app#creatingcred)
2. `git clone https://github.com/openid/AppAuth-Android.git`
3. The following diff shows where to plug in the discovery_uri for google and the client ID from step 1
```
diff --git a/app/build.gradle b/app/build.gradle
index 26ef381..fc62ed1 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -12,7 +12,7 @@ android {
         // Make sure this is consistent with the redirect URI used in res/raw/auth_config.json,
         // or specify additional redirect URIs in AndroidManifest.xml
         manifestPlaceholders = [
-                'appAuthRedirectScheme': 'net.openid.appauthdemo'
+                'appAuthRedirectScheme': 'com.googleusercontent.apps.YOUR-CLIENT-ID'
         ]
     }
 
diff --git a/app/res/raw/auth_config.json b/app/res/raw/auth_config.json
index 6f39e24..13a0fed 100644
--- a/app/res/raw/auth_config.json
+++ b/app/res/raw/auth_config.json
@@ -1,8 +1,8 @@
 {
-  "client_id": "",
-  "redirect_uri": "net.openid.appauthdemo:/oauth2redirect",
+  "client_id": "YOUR-CLIENT-ID.apps.googleusercontent.com",
+  "redirect_uri": "com.googleusercontent.apps.YOUR-CLIENT-ID:/oauth2redirect",
   "authorization_scope": "openid email profile",
-  "discovery_uri": "",
+  "discovery_uri": "https://accounts.google.com/.well-known/openid-configuration",
   "authorization_endpoint_uri": "",
   "token_endpoint_uri": "",
   "registration_endpoint_uri": "",

```
4. `./gradlew :app:installDebug`

Thanks!

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
