### ISSUE TITLE
omnibox API for mobile

### ISSUE THREAD

**Issue by atahabaki** [kiwibrowser/src#283]
Hi, I'm developing an extension which uses `omnibox API` ([smartbox](https://github.com/atahabaki/chrome-smartbox)).

And I wanna use it on mobile. Could you please enable it? :smile:

**Comment by d3ward** [comment]
I see you discontinued the project 
Check out latest Kiwi builds and if need help, open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
