### ISSUE TITLE
Extensions folder

### ISSUE THREAD

**Issue by sn0vv** [kiwibrowser/src#284]
I try to modify an extension, so I'd like to know where Kiwi Brower stores extensions.

I can find the extension folder for Windows Chrome at:
\AppData\Local\Google\Chrome\User Data\Default\Extensions

Thanks.

**Comment by ZhymabekRoman** [comment]
Hello!
You can only access the chrome extensions folder if you have root permissions.
Path to the folder with extensions: /data/data/com.kiwibrowser.browser/app_chrome/Default/Extensions/

**Comment by sn0vv** [comment]
Thank you for your information!
I can access the chrome extensions folder now.

**Comment by ZhymabekRoman** [comment]
@sn0vv, please close issue
