### ISSUE TITLE
Feature Request: Support browsingData.RemovalOptions.origins and browsingData.RemovalOptions.excludeOrigins

### ISSUE THREAD

**Issue by rururux** [kiwibrowser/src#286]
First of all, thanks for the great app.
When I was creating the extension for kiwi, I noticed that this option was not supported.
It would be great if you could make it available.

related links:
https://developer.chrome.com/docs/extensions/reference/browsingData/#type-RemovalOptions
https://bugs.chromium.org/p/chromium/issues/detail?id=78093#c93
https://chromium.googlesource.com/chromium/src.git/+/adb9784ce48191d9e5ee669c6ecefe3b44872121

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
