### ISSUE TITLE
Some sites do not work as expected in Kiwi, but work fine on Chrome for android

### ISSUE THREAD

**Issue by imranzahid01** [kiwibrowser/src#287]
One website for example which doesn't work properly on Kiwi is [https://getbootstrap.com/docs/5.0/examples/dashboard/](https://getbootstrap.com/docs/5.0/examples/dashboard/). When you open the link and click on the hamburger link, nothing happens. This is not the case with Chrome for android.

**Comment by Oranko** [comment]
Fixed in the latest version
