### ISSUE TITLE
kiwi latest should have support for tab groups and it should have the option to behave like tabs in same window for better compatibility of add-ons with chrome.tabs API

### ISSUE THREAD

**Issue by mahfuzullah** [kiwibrowser/src#288]
the new chrome mobile has a feature called tab groups, which is awesome.... it lets me open a lot of tabs and keep them organised. its like opening a tab in a new window in desktop chrome.

and as not a lot of extensions have developed for this new feature's API, i think it should behave like tabs in other window in regards to API access to extensions.

**Comment by d3ward** [comment]
Check out latest Kiwi builds wich have tab groups too
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
