### ISSUE TITLE
Using Kiwi with Chrome Remote Debugging only gives a white page

### ISSUE THREAD

**Issue by fbartels** [kiwibrowser/src#29]
Hi @kiwibrowser,

I wanted to use [Chrome Remote Debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging) to investigate why a web application they we are developing behaves differently on Kiwi, than it does on Chrome. Sadly opening it just gives a white page (while opening remote debugging in Chrome afterwards works).

Kiwi 77.0.3865.92
Android 10.0.0 (Nokia 7 plus)

**Comment by kiwibrowser** [comment]
Hi, yes it's supposed to work
If you get a white page, it should work if you have access to Inspect fallback in chrome://inspect

If the option is greyed out or doesn't work then we can review together, it's one of the point listed at the end of the README (I already faced it)
Did you build it yourself or it's the Play Store edition ?

Thanks a lot for the feedback,

**Comment by fbartels** [comment]
Hi, or sorry I did not notice the section about remote debugging in the readme. But I am not sure if it applies to my situation.

I am using the version from the play store. Unfortunately I don't see a fallback link for inspect

This is how the debugging view currently looks for me:
![image](https://user-images.githubusercontent.com/1257835/79752518-ba83b600-8314-11ea-8780-430bb0ab776b.png)

I just noticed that there is a pending chrome update. I am currently on 80.0.3987.163, let me quickly restart to get the newest version.

**Comment by fbartels** [comment]
Ah, that was a good hint. My Chromium based Edge is already at 83.0.478.18 but indeed there I was able to use the remote debugging view.

**Comment by omarryhan** [comment]
I'm having the exact same problem

**Comment by jaynetics** [comment]
Chrome and plain Chromium don't work. Edge and Brave do. Maybe just put those in the Readme for now?

**Comment by d3ward** [comment]
With recents builds , Kiwi now have DevTools !

**Comment by kiwibrowser** [comment]
Also remote debugging works (just press Inspect fallback)
