### ISSUE TITLE
Display issue on 19.5:9 screens

### ISSUE THREAD

**Issue by cbwee** [kiwibrowser/src#290]
My phone is POCO M3, when I use Kiwi Browser on it, sometimes there is a black bar appearing at the top of the screen, and I always have to close the browser to make Kiwi Browser display normally again. Other Chromium-based Android browsers do not have this issue.

Edit: Brave Browser and Adblock Browser on Android have the same issue.

<img src="https://user-images.githubusercontent.com/34395942/104091080-f2e86d00-5272-11eb-9ff4-a53d31d0d0e1.jpg"  width="250">

**Comment by CB-wee** [comment]
The screen resolution is 1080 * 2340

**Comment by ItsCubeTime** [comment]
I have a Samsung A40 (also 1080x2340px)

Another issue is with the video player of which the buttons and sliders are displayed slightly outside of the screen

**Comment by ItsCubeTime** [comment]
I dont have the issue OP mentions however, nothing Ive noticed at least

**Comment by devilstars** [comment]
Same issue (mi9 lite) on android 11. It's ok on android 10.

**Comment by CB-wee** [comment]
My POCO M3 has Android 10 with MIUI 12, but it still has the same display issue, the black bar at the top, even after updating Kiwi Browser to the latest version.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)

**Comment by ItsCubeTime** [comment]
> Check out latest Kiwi builds
> If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)

Thank you for fixing all these small issues left and right :) I noticed today that the app no longer crashes when rotating the display whilst watching a video <3 I have no idea how many times it crashed on me in the past so Im quite happy about that one
