### ISSUE TITLE
Feature Request: Bookmark Organization 

### ISSUE THREAD

**Issue by Reginwulf** [kiwibrowser/src#291]
Having the **ability to sort** the **bookmarks** like in the **mobile** version of **_Vivaldi_** would be great. Like **manual, alphabetically, ascending and descending, etc.** Really useful since **most extensions for bookmarking don't work** on **mobile** it seems or only partially work. Also maybe include additional speed dial like _Vivaldi_ with sort capabilities too possibly.

**Comment by d3ward** [comment]
That feature is available on latest Kiwi builds at [src.next](https://github.com/kiwibrowser/src.next)
