### ISSUE TITLE
The login slider failed to verify or could not slide.

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src#292]
The login slider failed to verify or could not slide. Chrome does not have this problem.
![Screenshot_20210117_234821_com kiwibrowser browser](https://user-images.githubusercontent.com/55195642/104848325-10888880-58aa-11eb-84ae-54c1073ccd36.png)
![Screenshot_20210117_234832_com kiwibrowser browser](https://user-images.githubusercontent.com/55195642/104848334-18e0c380-58aa-11eb-8a8a-7b63f6f38b3f.png)

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
