### ISSUE TITLE
Alert message not showing

### ISSUE THREAD

**Issue by abcdef117532** [kiwibrowser/src#293]
alert() messages do not show in Kiwi but Chrome works perfectly.

I found out this problem when I was using Tampermonkey as if user wants to delete one of the scripts, it will pop up the alert box to ask for confirmation but because of this bug I cannot delete the script.

You can use this link to test:
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert

**Comment by kiwibrowser** [comment]
Hello,

Thanks for the report, Kiwi has different behaviour than Chrome related to alert() windows when the alert()/confirm() dialogs are located inside an iframe (the main idea is that an iframe should not be able to interfere with the focus of the main window). I'll think about a solution and get back to this topic.

**Comment by Serega007RU** [comment]
It doesn't matter if it's in an iframe or not. It doesn't work without an iframe either

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
