### ISSUE TITLE
BUG: Incognito Window Notification became unresponsive

### ISSUE THREAD

**Issue by merrcury** [kiwibrowser/src#295]
**App Version**: Git201105Gen347353974
**OS**: Android 7.0.0; Redmi Note 4 Build/NRD90M

**Issue**:  If I close Kiwi Browser from Recents tab with Incognito Tabs open, Notification goes unresponsive. 
**Expected Behaviour**: No Kiwi Browser notification of Incognito after clearing all apps from recent. 

**Steps to Reproduce**:
  + Open Kiwi Browser 
  + Open Incognito Window and Open some random site 
  + Press the Home button on the device and use some another app. 
  + Now, kill all apps from recent. 
  + Check Notification Area.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
