### ISSUE TITLE
Unusable extensions in private browsing mode.

### ISSUE THREAD

**Issue by Beatz106** [kiwibrowser/src#298]
### Current environment

- **LineageOS 17 (Android 10)**
- **Browser version: Git210108Gen470813741**
- **Extension tested: Ublock Origin, LastPass, Universal Bypass, Ghostery**
- **Website used for testing: ESPN**

### Steps to reproduce

- Go to the Chrome Web Store and download Ublock Origin (this extension will be used as an example, it doesn't matter if you download anything else)
- After installing go to "Extensions" and activate the development options, then go to the extension settings and make sure that the following is activated: 
![Screenshot_20210123-144020_Kiwi_Browser](https://user-images.githubusercontent.com/74375581/106239817-da5fd880-61c8-11eb-9e54-adc845c79741.png)

### Expected behavior:

- When visiting the website, the blocked content counter should be present in the extension icon, even when going to the extension page, the main page should be present. 
![Screenshot_20210129-000837_Kiwi_Browser](https://user-images.githubusercontent.com/74375581/106240187-738eef00-61c9-11eb-9176-f0cca4f04d70.png)

### Current behavior:
- Just a blank screen is displayed. 
![Screenshot_20210129-000854_Kiwi_Browser](https://user-images.githubusercontent.com/74375581/106240307-adf88c00-61c9-11eb-83d0-802148ebfb22.png)

Of course, there is no counter next to the extension icon, and for obvious reasons, there is ads on the pages that are visited.

**Comment by amine250** [comment]
I'm running into the same issue, extensions seem to be inactive in private browsing mode, even when they're allowed to run in it.

**Comment by QuantumGitHub** [comment]
I am running the Kiwi Browser on Android 8 and have the same behavior. I enabled the extensions, such a uBlock origin, Leechblock, BitWarden to also run in Incognito Mode and they aren't working when in Incognito Mode.
All extensions that I have tried were working in normal mode.

**Comment by d3ward** [comment]
#36

**Comment by Beatz106** [comment]
Unless the solution to the problem does not exist yet, the thread should not be closed.

**Comment by d3ward** [comment]
This issue is a duplicate ...
