### ISSUE TITLE
`chrome.runtime.getPlatformInfo` returns `Platform information unavailable` makes some plugin does not work correctly

### ISSUE THREAD

**Issue by dev-techmoe** [kiwibrowser/src#301]
IDK why this API returns this value on Kiwi, and it causes some extensions (e.g. [uBlacklist](https://github.com/iorate/uBlacklist)) does not work correctly (cannot enter config page, [Here is some code calls this API in this extension](https://github.com/iorate/uBlacklist/blob/16f720d91d77233268145ebcbcc0648703bce4b2/src/scripts/options/options-context.tsx])), maybe it's a browser problem? Thanks.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
