### ISSUE TITLE
Add support for Android accessibility API

### ISSUE THREAD

**Issue by d3ward** [kiwibrowser/src#31]
This should enable autofill of passwords from password managers ( Bitwarden,LastPass etc. )

**Comment by rururux** [comment]
chromium have a bug for Autofill:[Link](https://github.com/bitwarden/mobile/issues/489)

**Comment by qiforra** [comment]
> This should enable autofill of passwords from password managers ( Bitwarden,LastPass etc. )

Very nice

**Comment by yaakovfeldman** [comment]
Bitwarden already works with the play store version.

**Comment by Mar2ck** [comment]
Using Keepass2Android, Firefox works fine but Kiwi doesn't

**Comment by makeway4pK** [comment]
At least it should be possible to enable the **manual** username/password autofill that is available in nearly every single line textbox all over the Android OS, except any in Kiwi Browser

By the manual option I mean:
Long tap on a textbox -> three dots -> Auto-fill -> Pick a saved password (drop down)

This opens the Google Play Services password manager that shows any passwords stored in your Google account. I keep my work n personal accounts separate so, I don't have a privacy issue with Google.

My current workaround is to use a to do app's quick add textbox to get my password and cutting n pasting it to the webpage, inconvenient.

**Comment by Greco1899** [comment]
I am unable to get the Bitwarden app's auto fill to pop up still but I have no issues with Chrome.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> Using Keepass2Android, Firefox works fine but Kiwi doesn't

https://github.com/PhilippC/keepass2android/issues/834

**Comment by mirsella** [comment]
i'm using keepassDX, it work with chrome but not with kiwi

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Using Keepass2Android with chrome works fine but with Kiwi doesn't

**Comment by mirsella** [comment]
> Using Keepass2Android with chrome works fine but with Kiwi doesn't

yep that why i think maybe it's kiwi which isn't supporting it ?

**Comment by d3ward** [comment]
[src.next#64](https://github.com/kiwibrowser/src.next/issues/64)
