### ISSUE TITLE
Add an option to disable translator 

### ISSUE THREAD

**Issue by hefty-fading-culprit-epiphany-drew** [kiwibrowser/src#310]
Currently in kiwi there has to be a translator always selected, among the given options all are privacy invasive and they have access to sites we visit, so please provide users the option to disable translator

**Comment by rururux** [comment]
This page is about Chrome Android, but Kiwi has the same option.
https://www.bestusefultips.com/stop-google-chrome-to-translate-a-page-on-android/

**Comment by kiwibrowser** [comment]
Hello,

The automatic translation feature that triggers on the current page and sends content without user interaction doesn't exist in Kiwi as it relies on Google Translate API keys (which we don't have).
With regards to the language detection it's done locally on the phone using cld3 https://github.com/google/cld3 - so, if you don't click on the Translate button, then translation is not triggered at all.

I hope it answers your question :)
Arnaud.

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
Thanks for clarifying 😊

**Comment by kiwibrowser** [comment]
Thanks for thanks ! @hefty-fading-culprit-epiphany-drew
