### ISSUE TITLE
Add dns over https 

### ISSUE THREAD

**Issue by ghost** [kiwibrowser/src#311]
This is already present in upstream chrome

**Comment by amine250** [comment]
You can set it up on android's settings

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
> You can set it up on android's settings

Not on old Android devices

**Comment by yaakovfeldman** [comment]
This is maybe a bit niche but I find it really useful to have it in the browser. My android private dns is set to Nextdns for system wide adblock but in the browser I prefer to use an extension for adblock as its more flexible and I can disable it selectively. This requires the browser to override the system dns. Some builds of Firefox android can do this.

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
