### ISSUE TITLE
In desktop mode, the JavaScript object navigator.useragent is incorrect while open new tab by clicking on HTML like < a href=example.html target=_blank >

### ISSUE THREAD

**Issue by Apollo2nd** [kiwibrowser/src#314]
Set browser prefer desktop mode , open new tab by clicking on "<a href=example.html target=_blank >example</a>" , the User-Agent string will presented in mobile version. This issue cause a lot of websites displayed in mobile version, since they check User-Agent locally then redirect to mobile version pages. A temporary solution is installing extension force all pages open in current tab, but it is not a good experience. Hope someone will fix it, thanks.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
