### ISSUE TITLE
KiwiBrowser Aw Snap!  Big problem

### ISSUE THREAD

**Issue by Havanur888** [kiwibrowser/src#316]
In the latest version of the kiwi browser, I get this error when watching videos or browsing pages on Twitch , Twitter. "Aw Snap!" page. but when I downloaded the old version (December 18-2020) there is no problem. my device: Xiaomi Note 3 (arm64v8a)

**Comment by kiwibrowser** [comment]
Hello @Havanur888 

Thanks a lot for reporting the issue,
I see, I'll make a test build with different rendering setting (though I haven't experienced the issue myself) and push it and see if this reduces the amount of crashes reported on the Play Store.

Did you find a way to reproduce it ? Was it only pages with videos or a bit everywhere ?

**Comment by Havanur888** [comment]
Thanks for your reply 
I get the same mistake every 20 minutes on average while browsing the page on twitter and watching videos on twitch. Of course, this problem only happens in the last update version. I did not get any errors in my previous version. but I know that I have to use the last version to avoid security vulnerabilities. how can we solve this smooth version 18 december 2020 https://www.apkmirror.com/apk/geometry-ou/kiwi-browser-fast-quiet/kiwi-browser-fast-quiet-git201216gen426127039-release/kiwi-browser-fast-quiet-git201216gen426127039 -android-apk-download / Android version 7.1.1 Xiaomi note 3

**Comment by HunterZ** [comment]
I am no longer able to play any videos on Twitter in Kiwi. It flickers a message saying "The media could not be played."

**Comment by Oranko** [comment]
Fixed in the latest version
