### ISSUE TITLE
Link causes crash 100% of the time

### ISSUE THREAD

**Issue by ballo** [kiwibrowser/src#317]
I've tried this link in both normal and incognito tabs to no avail. It will start to load but when fully loaded causes a crash:
https://reason.com/2021/02/11/biden-administration-suspends-rule-protecting-businesses-from-banking-discrimination/

**Comment by ballo** [comment]
I can't seem to copy the version info so I had to take a screen shot
![Uploading Screenshot_20210215-090703_Kiwi Browser.jpg…]()

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
