### ISSUE TITLE
Maps integrated to websites won't scroll

### ISSUE THREAD

**Issue by Godecki** [kiwibrowser/src#318]
Every time I encounter a built-in Google Maps on websites, they won't scroll. Maps won't detect two fingers used to scroll. Sometimes ir does scroll, but with severe lag and the map position resets every time I touch it. I've had this problem for around 2 years on diffetent devices really. Here is an example site with this problem: https://developers.google.com/maps/documentation/javascript/adding-a-google-map

**Comment by Oranko** [comment]
Fixed in the latest version
