### ISSUE TITLE
Upgrade to latest chromium 

### ISSUE THREAD

**Issue by LifeIsStrange** [kiwibrowser/src#320]
When will kiwi not just fake the user agent but actually upgrade? Many sites are broken and performance is sub par  in the meantime.
How can I know from the browser the real chromium version? (not the user agent faking)
@kiwibrowser it's been years 😔

**Comment by scorpion421** [comment]
`Kiwisource branch is Chromium 77.0 + Kiwi backported fixes, will show 88.0.4324.152 to websites for compatibility reasons (64-bit)`

You get this by inserting kiwi://version

**Comment by Oranko** [comment]
It has now been updated to the latest chromium :)

**Comment by LifeIsStrange** [comment]
Finallyyyyy
