### ISSUE TITLE
Please add a browser full screen feature

### ISSUE THREAD

**Issue by LazyCushion** [kiwibrowser/src#326]
I use the kiwi browser to browse **desktop web pages**, the phone is in **landscape** mode, but the **system status bar** and the **browser toolbar** occupy too much screen position. I hope to add a **full screen** function, the entire screen is used to display the page content .

**Comment by N00B2** [comment]
That would be cool! Is there work in progress?

**Comment by LazyCushion** [comment]
https://play.google.com/store/apps/details?id=immersive.duna.com.immersivemode&hl=zh&gl=US
我找到了一个可以达到让chrome全屏的应用.
