### ISSUE TITLE
Github is no longer working

### ISSUE THREAD

**Issue by LifeIsStrange** [kiwibrowser/src#327]
Github says that kiwi is an unsupported browser.
Link to this
https://docs.github.com/articles/supported-browsers

**Comment by csehszlovakze** [comment]
Unless you encounter serious bugs you can safely ignore that page. Vivaldi (desktop) isn't listed either yet it works perfectly (as I'm typing this).

**Comment by d3ward** [comment]
Check out latest Kiwi builds
