### ISSUE TITLE
Adjustments for dark mode

### ISSUE THREAD

**Issue by 0ibaba** [kiwibrowser/src#328]
Guys I'm so happy to see activity here, kiwi is personally my favourite browser.

Honestly it would be better if dark mode didn't dim text from white, it's harder to see things. Plus currently the dark mode also makes other colors in the webpage greyish and less vibrant.

Also having a night mode that's not pitch black would also be really nice. Firefox has nailed this look imo.

Personally I use dark reader and I like it's default look but if I don't turn on the dark mode(of kiwi) other ui elements will be white, but if I enable it, things look less vibrant.

Hope you guys will do something about this.

**Comment by Oi-Baba** [comment]
For example look at the github logo here
With night mode (using dark reader) :
![Screenshot_20210310-012345_Kiwi Browser](https://user-images.githubusercontent.com/69052158/110529480-54c43680-813f-11eb-8c0b-0fcc158ae74e.jpg)

Without nightmode (using dark reader)
![Screenshot_20210310-012353_Kiwi Browser](https://user-images.githubusercontent.com/69052158/110529647-850bd500-813f-11eb-9ce5-4158a99685bb.jpg)

**Comment by Oi-Baba** [comment]
Another suggestion would be to have a theme that makes just the UI dark so that it doesn't mess with the web pages, having pitch black and a greyish theme would be nice

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
