### ISSUE TITLE
Browser makes it difficult to use non-googlr search

### ISSUE THREAD

**Issue by ballo** [kiwibrowser/src#331]
If I set my default search to a non-google search like startpage, if I happen to use google it takes over the address bar which has various annoying effects such as not being able to copy the url. If google is not my search default it should treat a google search like any other web site.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
