### ISSUE TITLE
Kiwi makes it difficult to copy url or manipulate url

### ISSUE THREAD

**Issue by ballo** [kiwibrowser/src#332]
If you want to copy a url you have to currently:
Tap-hold the url to bring up the popup
Tap the elopsis for more options
Tap select all
Tap copy

When you tap-hold initially it should select the entire url by default.

 It's also devilishly difficult to edit the url or copy part of the url. I suggest when you tap-hold the url the field becomes a text field. Currently to edit a url you have to copy the url (four step process) then paste in a notepad somewhere, edit it, then repeat the process. It's very cumbersome

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
