### ISSUE TITLE
Major bug: Delete torrent deletes the file

### ISSUE THREAD

**Issue by ballo** [kiwibrowser/src#333]
So after spending an entire day downloading a file I selected "Delete torrent" expecting the same behavior as the desktop version of BiglyBt. Whoops! Big mistake! Instead of deleting the torrent, it deleted a huge file I needed. Nice!

Not sure what other nasty surprises await me. Any other clients out there? Also, why must you call quitting the app "shutdown service" like I'm running a windows print server? How about just Quit?

**Comment by d3ward** [comment]
That doesn't seems to be a Kiwi fault , anyway Kiwi has been updated to latest chromium
