### ISSUE TITLE
White text on white background in standard authentication dialog fields when dark mode is enabled

### ISSUE THREAD

**Issue by colinardo** [kiwibrowser/src#335]
Hello kiwibrowser team,
i noticed a dark mode problem when using standard authentication in websites. The input fields then use white text on white background, so you have to blind type ;-):

![screenshot](https://user-images.githubusercontent.com/30898477/111341818-292ed800-867a-11eb-8f94-89cd7e0ef5d0.png)

Regards
colinardo

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
