### ISSUE TITLE
Provide an updated roadmap?

### ISSUE THREAD

**Issue by mindplay-dk** [kiwibrowser/src#336]
The [Roadmap](https://github.com/kiwibrowser/src#roadmap) section in the README says:

> Later in the year, if there is enough demand and ressources, Kiwi will follow Chromium releases automatically (including bugfixes).

This was written in May 2020, and it doesn't look like you are following Chromium releases still?

It said, "if there is enough demand and ressources" - I think there's demand? But I don't know how you would measure that. Firefox allows just a few extensions, and I don't think there's any other Android browser that supports extensions, so I think Kiwi is definitely filling a gap. I'm guessing you just haven't had the resources?

I've reluctantly started using Vivaldi instead - it's better than Chrome, but I'm not really happy. There are plenty of things in Kiwi that I'm missing, but running a very old version of JS/DOM/BOM has just not been a good experience - too many websites break down or misbehave. (I imagine there's been many security patches over the years that are missing in Kiwi as well?)

Is there an issue to track the automation of integrating the Chromium changes?

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
