### ISSUE TITLE
Bug: Enable "Desktop Mode by default" enables "Mobile Site" by default

### ISSUE THREAD

**Issue by tobwz** [kiwibrowser/src#338]
I enabled in

Settings--->Accessibility---->Desktop Mode by default=YES

Then I exit + restarted Kiwi Browser (on Android 10).
When I open now the 3-dot menu I can see that

Mobile Site=YES (enabled)

Thats the opposite of what I expected.

I think this is a bug.

If users specify "Desktop mode" as default this should always be taken and now secretly switched to "Mobile site" mode.

Can you fix this?

Thank you

**Comment by d3ward** [comment]
[src.next#62](https://github.com/kiwibrowser/src.next/issues/62)
