### ISSUE TITLE
Feature Request: Allow rename of Speed Dial labels below Shortcut Thumbnails

### ISSUE THREAD

**Issue by tobwz** [kiwibrowser/src#339]
One of the most important features of Kiwi Browser are the Speed Dial Shortcut Thumbnails on every new tab.

Unfortunately the label below each Speed Dial Shortcut Thumbnail starts always with the domain name of the underlying URL/Internet address.

So if I have multiple Speed Dials to the same site and (long) domain name I cannot distinguish between them.
Even worse they all have the same Thumbnail picture since the all belong to the same domain.

So I would appreciate if users could rename the label below each Shortcut Thumbnail Speed Dial (of cause without
changing the Link/URL).

Can this be added in the next release?

Thank you

**Comment by d3ward** [comment]
There are alternative like [nextntp](https://github.com/d3ward/nextntp)
