### ISSUE TITLE
Improve code review tooling

### ISSUE THREAD

**Issue by kiwibrowser** [kiwibrowser/src#34]
Thread to discuss different possibilities to attach the Git repository to code review solutions. 

Example:
https://github.com/marketplace/codacy
https://github.com/reviewdog/reviewdog

Keep in mind different points:
 - The primary goal is to reduce bugs and security risks
 - The secondary is to keep the code simple
 - The third is to give relevant suggestions

Arguing 2 spaces or 4 spaces is ok, but far from critical.

We can afford proprietary solutions if the pricing is decent.

**Comment by kiwibrowser** [comment]
Important language coverage:
 - Java
 - C++

Optional:
 - shell
 - ninja (that would be a dream, but not sure it exists)

**Comment by kiwibrowser** [comment]
Other possibilities:  CodeClimate, Codacy and CodeFactor

**Comment by Kreyren** [comment]
Responding to https://github.com/kiwibrowser/src/pull/17#issuecomment-616557334

> I checked and there is no point to argue since shellcheck is already installed in the base image, and even after apt-get upgrade it doesn't change the version.
The image provides 0.4.6 in all cases, which is somewhat outdated compared to some other shellcheck solutions from GitHub Actions marketplace.

You are correct, debian stable provides an outdated 0.5.0 version, to fix this we can use `debian:testing` container

> This way we benefit of simplified management, updates and integration within GitHub comment and review process.

then this may be a solution https://www.codacy.com/

**Comment by kiwibrowser** [comment]
In test:

Sorry,
Codacy failed to analyse this repository, something went wrong on our side.

**Comment by Kreyren** [comment]
@kiwibrowser never happend to me, maybe try pinging them in: 
![image](https://user-images.githubusercontent.com/11302521/79819806-12f59a80-838b-11ea-90ba-d78f094cbec0.png)
