### ISSUE TITLE
Object.fromEntries missing

### ISSUE THREAD

**Issue by derjanb** [kiwibrowser/src#341]
According to [Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries) Object.fromEntries should be present at Chrome 73 and above, and Kiwi says it is based on Chrome 88, but Object.fromEntries is missing.

Kiwi: Git210216Gen57053602
User-Agent: "Mozilla/5.0 (Linux; Android 7.1.2; Nexus 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36"

Related issue: https://github.com/Tampermonkey/tampermonkey/issues/1197

Thanks.

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
