### ISSUE TITLE
Twitter Videos unavailable

### ISSUE THREAD

**Issue by ghost** [kiwibrowser/src#344]
No matter how I tried,it did not work.

**Comment by bramaudi** [comment]
I experience weird behavior too, needed a touch to make twitter loaded.

Also trying run modern css scroll snap and not working as expected.

https://user-images.githubusercontent.com/14371119/114618238-a6109a00-9c98-11eb-9895-af99ee817d39.mp4

**Comment by bigrain2007** [comment]
user agents:iphone

**Comment by joserealdev** [comment]
Yep, I'm facing this problem too

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
