### ISSUE TITLE
Tampermonkey unaviliable

### ISSUE THREAD

**Issue by Zhang-Jun-ei** [kiwibrowser/src#346]

**Comment by dagaz** [comment]
The Problem is that Kiwi does not update the extension. 
The newest Version (4.13) works fine. But - as the extension does not update you have to reinstall it and install you scripts again. (Or you can import your scripts and settings from a file - if existing.)

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
