### ISSUE TITLE
manually loading zip files not working, crx files working

### ISSUE THREAD

**Issue by AntonOfTheWoods** [kiwibrowser/src#347]
I naively believed Google when they said "they're the same", but trying to install via a .zip was failing silently so was desperately trying to think of a solution for testing my extension on both Yandex and Kiwi. Then I came across a post from 2010 saying "they're not the same, do `chrome.exe --enable-apps --pack-extension=<path\to\app\folder>` and it will work". So I did, and it worked. I wasted quite a lot of time on this - is there anywhere to document this to avoid others wasting time too?

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
