### ISSUE TITLE
Blob "text is not a function"

### ISSUE THREAD

**Issue by AntonOfTheWoods** [kiwibrowser/src#348]
I am trying to run an extension, which works ok in the Yandex browser on Android (ok, so on one device it refuses to load but when it does load it runs fine!). On two devices (Xiaomi 11 and OnePlus 6) on Kiwi I am getting "text is not a function" when I am trying to get the text back from a `Blob` (`await myBlob.text()`). Debugging shows that indeed the object created doesn't appear to have a `text()` function. Very strange indeed. Needless to say, all the other platforms I've been testing on (FF and all Chrome variants) on the desktop do have a `text()` method, so the code works fine.

Am I missing something here?

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
