### ISSUE TITLE
How to recover lost tabs ?

### ISSUE THREAD

**Issue by redstoneleo** [kiwibrowser/src#349]
I accidentally tapped the 'quit' menu of kiwi, then I lost all my previously opened tabs, any way to recover them back? If not possible, I think I should back up the history of kiwi, how? Thanks very much!

**Comment by hltdev8642** [comment]
look in these directories, but only if you are comfortable working with system files (and such) :

1)
 `/data/data/com.kiwibrowser.browser/app_tabs` 
The `0` directory is tabs direct from the browser (probably empty if you just closed/lost the tabs). 
The `custom_tabs` is exactly what if says it is (the custom tabs generated by other apps on your device). 

2) 
`/data/data/com.kiwibrowser.browser/app_chrome/Default`

Look in the `database` folder, and also the `History*`, `Cookies*` and `Visited Links` files (amongst others). They are DBs that open with any sql/database reading apps, and may contain some of the lost tab info if sorted accordingly). The History file is in my opinion the best way to get the tabs "back" (in a sense), by sorting the database by the date/id fields (the end of the list is likely your previous opened tabs).

Hope this is in the right direction towards what you were looking for :-)
