### ISSUE TITLE
TypeError: WebAssembly.instantiate is not a function

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [kiwibrowser/src#351]
TypeError: WebAssembly.instantiate is not a function

I'm using the Ruffle (Flash Player Emulator) extension, but it doesn't work on this browser. Can it be fixed?

Link to the extension: https://ruffle.rs

Link to The Ruffle demo test:
https://ruffle.rs/demo/

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
