### ISSUE TITLE
Crashes on page with embedded PDF

### ISSUE THREAD

**Issue by SumatraPeter** [kiwibrowser/src#354]
Example page that crashes the browser (causes it to force close): https://github.com/QiushiWu/QiushiWu.github.io/blob/main/papers/OpenSourceInsecurity.pdf

This is with the latest stable Play Store APK version from https://github.com/kiwibrowser/src/releases/tag/345153190 on an [Android 5.0.1 tablet with an Intel Atom CPU](https://www.gsmarena.com/lenovo_yoga_tablet_2_pro-6852.php).

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
