### ISSUE TITLE
Kiwi not rendering top part of NY Times site

### ISSUE THREAD

**Issue by darose** [kiwibrowser/src#358]
I'm running Kiwi version Git210216Gen570536402 on my Google Pixel 4a.  I've had a few problems with it on certain site pages before (such as on the Daily Beast login page) but nothing major.  But recently Kiwi stopped working correctly on the New York Times web site.  The entire top part of the site's home page doesn't get rendered.  (Or, more accurately, it actually does get rendered while the page is in the midst of loading, but then it disappears once the page load is complete.)

You can see a screenshot of what I'm referring to at:  http://darose.net/Screenshot_20210505-085458.png  Notice that the main headlines for the web site - which should be displayed above the 2 black lines at the top - are missing.  For contrast, here is how the site renders (correctly) in the Chrome browser on the same device:  http://darose.net/Screenshot_20210505-085529.png

Would love to know what the problem might be, and whether there's a fix or workaround for it.  Kiwi has been my main browser on my phone for a while now, but I won't be able to keep using it if it can't display important sites correctly.

**Comment by untoldone** [comment]
I see the same on Galaxy S9 on Android 10  w same version of Kiwi -- so I assume it's not device specific / specific to @darose

**Comment by austinhuang0131** [comment]
Can reproduce on Sony Xperia XA2 (H3123) Android 9, same version of Kiwi.

**Comment by d3ward** [comment]
Fixed on latest builds
