### ISSUE TITLE
window.open from extension background page is opening a blank tab

### ISSUE THREAD

**Issue by dellagustin** [kiwibrowser/src#360]
Hello,

I am trying to use the extension [podStation](https://chrome.google.com/webstore/detail/podstation-podcast-player/bpcagekijmfcocgjlnnhpdogbplajjfn) in Kiwi.
It works fine on Chrome for Desktop.

In Kiwi, clicking the browser action button does not work as expected.

I am the author of the extension, the expected behavior is that clicking the button should open an extension page.

In the code I use `window.open`, but it does not work on kiwi as it works on chrome for desktop. It opens an empty tab instead.

I tested using `chrome.windows.create({url:'/podstation.html'})` instead and it worked, so there is a workaround.

**Comment by ashishpatel1992** [comment]
Hi @dellagustin ,
I am trying to debug kiwi into desktop using usb debugging but I couldnt access `chrome.windows` as it returns `undefined`.

**Comment by ashishpatel1992** [comment]
This works for me
```javascript
let wnx = window.open("about:blank");
wnx.location = "chrome-extension://bpcagekijmfcocgjlnnhpdogbplajjfn/podstation.html";
```
I will look for a workaround that should make it working on desktop as well as mobile.

**Comment by dellagustin** [comment]
Hello @ashishpatel1992 , thanks for the tip, I tried that on the console while remote debugging the background page on kiwi running on android, it did not work for me.

**Comment by dellagustin** [comment]
by the way, I debugged on android following this guide: https://developer.chrome.com/docs/devtools/remote-debugging/

here are some screenshots:
![image](https://user-images.githubusercontent.com/260113/119231579-e679f800-bb21-11eb-9c1e-2922f6a5c40e.png)

![7ec9e5a6-0222-4dd5-8404-0443112eeb08](https://user-images.githubusercontent.com/260113/119231619-1cb77780-bb22-11eb-9e7c-0ad5704db443.jpg)

In my experience you have to click the podStation button for the background page to be loaded.

**Comment by dhara03** [comment]
Hi @dellagustin ,I'm facing the same problem, blank page is opening. And yes followed the same procedure like USB debugging, on debugging it's just showing plain <html> code. If you can help me around to open up the page with displaying design after that can surely check for the responsive UI.

**Comment by dellagustin** [comment]
Hello @dhara03, answered here: https://github.com/podStation/podStation/issues/56#issuecomment-846537720

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
