### ISSUE TITLE
Media Sessions from extension background pages are not shown on android notification bar and lock screen

### ISSUE THREAD

**Issue by dellagustin** [kiwibrowser/src#361]
Hello, 

I'm the developer of [podStation](https://chrome.google.com/webstore/detail/podstation-podcast-player/bpcagekijmfcocgjlnnhpdogbplajjfn).

This extension play media (podcasts) from the background page of the extension.

When testing, the media being played from the background page is not shown on the notifications drawer nor the lock screen.

I'm not sure it is worth investing in fixing this issue, as the extension manifest v3 will not support background pages, and currently it is not possible to play audio from the background using service workers.

References:
- https://bugs.chromium.org/p/chromium/issues/detail?id=1131236

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
