### ISSUE TITLE
Extensions wont update

### ISSUE THREAD

**Issue by dagaz** [kiwibrowser/src#362]
(I searched and I hope that this is no repost)

It seems that extensions wont be updated at all. 

I had installed Tampermonkey 4.12.
The version in the store was 4.13. 
Regardless where i clicked on update - it wont update the extension. The only option was to remove and reinstall it, which removed also all extension setting. :(

I really hope there is an easy solution.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
