### ISSUE TITLE
"Hide annoying ads" no longer works on YouTube

### ISSUE THREAD

**Issue by ballo** [kiwibrowser/src#364]
I understand if this is a Google Play issue, but I quite frankly don't give a poop about Google Play (or anything Google). Why not put the APK on fdroid and on GitHub? This browser used to be very useful as I could stream audio with it using Audio Only YouTube. No longer! Even if I listen to "annoying ads" the browser will reset the audio stream from the beginning instead of resuming.

Does anyone host the non-sucky version of Kiwi Browser anywhere?

**Comment by ballo** [comment]
I would settle for downgrading the browser to the functional version if someone could explain to me how to do that. Thanks.

**Comment by Shihabus-Sakib-Rad** [comment]
Install [ublock origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) for adblock.
Go [here](https://github.com/kiwibrowser/android/issues/60#issue-442779973) for background playback
