### ISSUE TITLE
kiwi now has some kind of ultra annoying popup magnifier

### ISSUE THREAD

**Issue by ballo** [kiwibrowser/src#365]
Sigh, this used to be such a nice alternative to Brave. I'll just attach a screen shot of the stupid feature nobody asked for and seemingly cannot be bypassed. It happens whenever I click a small link.

Is there anyway to downgrade to the older version?
![Screenshot_20210526-155552_Kiwi Browser](https://user-images.githubusercontent.com/631311/119736648-45e64980-be3b-11eb-9c68-f12502d21ac2.jpg)

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
