### ISSUE TITLE
Error 400 when trying to view extension page

### ISSUE THREAD

**Issue by ballo** [kiwibrowser/src#366]
The only way to view an extension page is to use private browsing. You cannot install an extension from a private browser window. I tried to disable all extensions to no avail.
![Screenshot_20210526-160009_Kiwi Browser](https://user-images.githubusercontent.com/631311/119736940-bf7e3780-be3b-11eb-88af-711503b85d37.jpg)

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
