### ISSUE TITLE
Feature Request: Optional Chaining support

### ISSUE THREAD

**Issue by Sashank999** [kiwibrowser/src#369]
Heya !

How about supporting optional chaining ?

I work on a Chrome Extension and we have a lot of cases where optional chaining just reduces a lot of code and increases readability.
Ofc we could use BabelJS but Chrome Web Store has manual checking of all extensions which delay our extension updates too much.

I'm sorry if I said something wrong. But this is part of the ECMAScript standard. How can you guys call Kiwi a Chromium-based browser when it doesn't support all of the features Chromium doesn't ? Well atleast Kiwi should obey the standards...

Manifest V3 isn't a standard. It is just enforced by Chrome upon us. I can completely understand not adding support for Manifest V3. I don't support V3. But just ignoring standards isn't too good for the Kiwi Browser itself.

I have never ever coded in languages other than HTML, CSS and JS so sorry if this is something hard to implement.

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)

**Comment by kiwibrowser** [comment]
(yes it's now supported)
