### ISSUE TITLE
Issue with status bar black-zone when selecting URL

### ISSUE THREAD

**Issue by ghiki** [kiwibrowser/src#374]
If you want to use "select all" function from Android in the URL field, when you select this action, it appears a black frame over It. This frame can't be removed until you close the browser
![Screenshot_2021-06-07-22-50-29-683_com kiwibrowser browser](https://user-images.githubusercontent.com/854302/121085938-d2e9b500-c7e2-11eb-8378-607d92f30f24.jpg)

You can see here:
https://youtu.be/89Dz61I90AY

**Comment by touhidurrr** [comment]
Is your browser fully updated? I tried it on my device and no such black zone. I am using Android 10.

**Comment by ghiki** [comment]
Yep, last update...maybe due Android versión?
This is POCO X3 Pro MIUI12
![Screenshot_2021-06-09-14-18-35-332_com kiwibrowser browser](https://user-images.githubusercontent.com/854302/121352946-a5f5e900-c92d-11eb-9fec-637116c1e625.jpg)

**Comment by touhidurrr** [comment]
Maybe it is an Android 11 Specific Bug then?

**Comment by joserealdev** [comment]
I'm facing the same problem. In my case is not just with "select all" functionality, I'm not able to copy url's (or at least a piece of it) from the navbar due that black frame. Pretty annoying.

Using Android 11 with MIUI 12.5

**Comment by ghiki** [comment]
Occurs basically when "long tap" in the address bar

**Comment by cbwee** [comment]
> Maybe it is an Android 11 Specific Bug then?

No, my phone is POCO M3, running MIUI 12 with Android 10, but it has the same issue.

And it looks like this issue only appears in Chromium-based browsers in MIUI, because on my phone, it also appeared in Brave Browser and Adblock Browser.

https://github.com/kiwibrowser/src/issues/290#issue-782594136

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
