### ISSUE TITLE
Bad logos

### ISSUE THREAD

**Issue by ygz213** [kiwibrowser/src#375]
I think they should fix.

![Screenshot_2021-06-14-19-27-42](https://user-images.githubusercontent.com/77006222/121928844-3e82d380-cd49-11eb-8f78-8aa05405d75f.png)
![Screenshot_2021-06-14-19-27-42_LI](https://user-images.githubusercontent.com/77006222/121928897-4c385900-cd49-11eb-878a-b2c003128d18.jpg)
![Screenshot_2021-06-14-19-27-54](https://user-images.githubusercontent.com/77006222/121928876-480c3b80-cd49-11eb-8d1f-e059cf236e7a.png)

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)

**Comment by ygz213** [comment]
<https://github.com/kiwibrowser/src.next/issues/116>
