### ISSUE TITLE
Could it support flash?

### ISSUE THREAD

**Issue by 1457384613gh** [kiwibrowser/src#376]
Could it support flash?
Could it support load swf files?
Like Puffin Web Browser, if only Kiwi Browser would support flash !
It would makes Kiwi more similar to a desktop web browser.

**Comment by dagaz** [comment]
I really hope not!

Flash is dead and a security risk!

**Comment by AdamWrighter** [comment]
> It would makes Kiwi more similar to a desktop web browser.

It really wouldn't. Desktop browsers are all dropping support for Flash. Doing new work to support Flash in 2021 would be absurd.

**Comment by d3ward** [comment]
As Flash is considered dead , we have to close that issue
