### ISSUE TITLE
Kiwi Browser crashes with activated "Keepa" extension

### ISSUE THREAD

**Issue by Tomcat86878** [kiwibrowser/src#378]
Dear Kiwi Browser Team,

First of all, thank you so much for this great browser, I use it on all of my devices and especially love the feature of the working Chrome extensions.

In the last couple of weeks I encountered a problem with the Chrome extension "Keepa", which is a price tracker for Amazon. If I load an Amazon product page and have the extension activated, Kiwi Browser will crash. This happens on my mobile (Google Pixel 5) as well as on my tablet (Amazon Fire HD 10). The extension itself is working on my desktop computer with Chrome Browser.

I don't know if the root cause is Kiwi Browser or the extension itself. But could you probably have a look at this?

Please contact me if I can help with logfiles or other debug information.

Thank you very much and best regards,
Tom

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
