### ISSUE TITLE
Web site reload loop

### ISSUE THREAD

**Issue by ballo** [kiwibrowser/src#379]
This link causes a reload loop of fail (brave works fine):
https://www.spectator.co.uk/article/laurel-hubbard-is-the-beginning-of-the-end-of-women-s-sports?

**Comment by ballo** [comment]
Sorry, this is probably due to Bypass Paywalls extension which works fine on the desktop chromium but not Kiwi

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
