### ISSUE TITLE
Hand button improvements

### ISSUE THREAD

**Issue by d3ward** [kiwibrowser/src#38]
The button is an exceptional feature but some people may find it annoying that when it scrolls up, it halves the visibility of the site .

The feature can be improved in two ways: 
- Add an option to select the scrolling mode (full, half, etc.). 
- Add long press or double tap to scroll without halving the screen 

Edit: The feature is now improved with a fixed hand mode . It is more comfortable

**Comment by kiwibrowser** [comment]
Related code:

Settings page layout:
https://github.com/kiwibrowser/src/blob/master/chrome/android/java/res/xml/accessibility_preferences.xml#L49

Settings controller: https://github.com/kiwibrowser/src/blob/master/chrome/android/java/src/org/chromium/chrome/browser/preferences/AccessibilityPreferences.java#L152

Toolbar (in phone mode, not available in Tablet mode):
https://github.com/kiwibrowser/src/blob/b1ea3ea95d8ac15fc0b49acd83ba2f8b1aaa8d2b/chrome/android/java/src/org/chromium/chrome/browser/toolbar/ToolbarPhone.java#L567

**Comment by kiwibrowser** [comment]
Toolbar layout: https://github.com/kiwibrowser/src/blob/b1ea3ea95d8ac15fc0b49acd83ba2f8b1aaa8d2b/chrome/android/java/res/layout/toolbar_phone_common.xml#L54

**Comment by kiwibrowser** [comment]
The code that is executed when you press the button: https://github.com/kiwibrowser/src/blob/b1ea3ea95d8ac15fc0b49acd83ba2f8b1aaa8d2b/chrome/android/java/src/org/chromium/chrome/browser/toolbar/ToolbarManager.java#L1103

**Comment by kiwibrowser** [comment]
MR #48

**Comment by marcusatiliusregulus** [comment]
i believe i remember it working but right now it does not: the page stays halfed when scrolling down

**Comment by d3ward** [comment]
> i believe i remember it working but right now it does not: the page stays halfed when scrolling down
> (version Git200915)

It's the new behavior of the hand button. Basically it's how it should be. It works like the split mode on Android, stays halfed until the user decide to exit the "one hand" mode.
