### ISSUE TITLE
Kiwi shows white page on some website

### ISSUE THREAD

**Issue by ghost** [kiwibrowser/src#380]
Like
https://docs.github.com
The page will appear in a flash, then kiwi only show a white page.
![Screenshot_20210628-070118_Kiwi_Browser](https://user-images.githubusercontent.com/37654896/123562089-04044680-d7df-11eb-9d5a-bf0614de3461.png)

**Comment by yehoshualee** [comment]
Network connection is fine. Page shows right on chrome.
![Screenshot_20210628-072733_Chrome](https://user-images.githubusercontent.com/37654896/123562636-7de9ff00-d7e2-11eb-9fad-79c91a4d0e4e.png)

**Comment by d3ward** [comment]
This has been fixed with latest Kiwi builds
