### ISSUE TITLE
"ghost" second bar when using the bottom bar. 

### ISSUE THREAD

**Issue by hhjeremy** [kiwibrowser/src#382]
To reproduce:
choose bottom bar
make sure you have 2 tabs open in a single tab group. 
Scroll down and the "extra" toolbar is there.

https://dl3.pushbulletusercontent.com/nN3htiHDVqq92isrzAAWWqNitOmxl5xi/VID-20210627-WA0000.mp4

**Comment by d3ward** [comment]
This has been fixed in latest builds. Still some bottom bar related bugs exist
