### ISSUE TITLE
How to change back to the new label view of the original style

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src#383]
In the next version, it is shown as Figure 1. In the old version, it is shown as Figure 2. The operation of Figure 2 is better than that of Figure 1.
Hope to add options to support Figure 2.
![Screenshot_20210630_211215_com kiwibrowser browse](https://user-images.githubusercontent.com/55195642/123967533-fc17f280-d9e8-11eb-8813-e178b865b64c.jpg)
![Screenshot_20210630_211209_com kiwibrowser browse](https://user-images.githubusercontent.com/55195642/123967546-fe7a4c80-d9e8-11eb-87b5-371afbed9cac.jpg)

**Comment by TsXor** [comment]
I think figure 1 is better for viewing,
So pls allow users to switch between these 2 tab views.
我觉得都挺好的，所以2种请都保留

**Comment by kiwibrowser** [comment]
Settings -> Tab switcher -> Grid

**Comment by TsXor** [comment]
> 
> 
> Settings -> Tab switcher -> Grid

I can't find "Tab Switcher". Is this only available in the next version?

**Comment by kiwibrowser** [comment]
Oh yes, and it will be in "Classic" / "Current" src version next week.

**Comment by drc5521** [comment]
> Oh yes, and it will be in "Classic" / "Current" src version next week.

yeah，i find it，but,It seems that there are still some problems, and the tabs cannot be swiped. So, I find one label is difficult while have many labels.  Second video is next version。I hope to be able to revert back to the first video mode.Thank you.

https://user-images.githubusercontent.com/55195642/124355620-b2c3df00-dc44-11eb-9639-575aefe398e9.mp4


https://user-images.githubusercontent.com/55195642/124355636-c707dc00-dc44-11eb-8def-fa5b5c6ec8ac.mp4

**Comment by d3ward** [comment]
Related issue are now available in [src.next](https://github.com/kiwibrowser/src.next)
