### ISSUE TITLE
In the next version, the new tab view cannot be collapsed when sliding

### ISSUE THREAD

**Issue by drc5521** [kiwibrowser/src#385]
In the next version, the new tab view cannot be collapsed when sliding. Figure 1 shows the next version, and Figure 2 shows the previous version.
 Obviously, the experience in Figure 1 is not as good as that in Figure 2.
![Screenshot_20210701_182819_com kiwibrowser browse](https://user-images.githubusercontent.com/55195642/124110202-93894e00-da9a-11eb-9b74-94b245725616.jpg)
![Screenshot_20210701_182852_com kiwibrowser browse](https://user-images.githubusercontent.com/55195642/124110209-95531180-da9a-11eb-859a-6ec7243588ec.jpg)

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
