### ISSUE TITLE
Bug: screen flashing with "Simplified view for open tabs" on

### ISSUE THREAD

**Issue by TsXor** [kiwibrowser/src#386]
After enabling "Simplified view for open tabs", screen will flash when entering a newtab or opened tab from the opened tabs list.
**This bug has already appeared in previous versions.**

**Comment by TsXor** [comment]
no this bug in next

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
