### ISSUE TITLE
New tab button grayed out

### ISSUE THREAD

**Issue by jeff93063** [kiwibrowser/src#389]
Sometimes the new tab button (the "plus" icon at the top left) is grayed out when it should not be, such as when there are no tabs running, or even when there are tabs. It is still active, and opens a tab as usual despite looking disabled.

**Comment by d3ward** [comment]
This seems to be fixed with latest builds 
Feel free to open an issue on [src.next](https://github.com/kiwibrowser/src.next) if bug persist
