### ISSUE TITLE
kiwibrowser Lite

### ISSUE THREAD

**Issue by Pantyhose-X** [kiwibrowser/src#392]
Lite uses kiwibrowser UI without a built-in kernel

**Comment by CrazyBoyFeng** [comment]
The current classic version (src) does use the system webview.  
The next version will have a chromium core in it.

I wonder if the author is going to abandon the classic version.

**Comment by Akshaygit1** [comment]
> The current classic version (src) does use the system webview.
> The next version will have a chromium core in it.
> 
> I wonder if the author is going to abandon the classic version.

Kiwi classic doesn't use system webview.
Both kiwi classic and kiwi next has chromium core and doesn't rely on system webview.

**Comment by CrazyBoyFeng** [comment]
Sorry I just realized I was wrong. kiwi git210216 is based on chromium 88.04324.152.

I'm also looking forward to seeing kiwi-lite, but I guess that would be a more limited implementation.

**Comment by d3ward** [comment]
There is no plan to have a lite version of Kiwi
The  features of Kiwi are there thanks to core chromium , removing that will mean that the browser will be too simple with no extensions , devtools, adblocker and so on
