### ISSUE TITLE
[Bug] In darkmode, everything isn't dark.

### ISSUE THREAD

**Issue by kyoyacchi** [kiwibrowser/src#394]
Just like as i said at the title.

There are some places aren't dark in dark mode.

Screenshot(s)
(Password Save or not question message)

![Screenshot_2021-07-20-11-41-14](https://user-images.githubusercontent.com/63583961/126290291-937e7177-24d2-4437-9bc5-e4d291c12423.png)

(Find in page)
![Screenshot_2021-07-20-11-43-34](https://user-images.githubusercontent.com/63583961/126290444-bce74ba7-e57d-4354-84a7-a038cd1b1e03.png)

(Add to home screen)
![Screenshot_2021-07-20-11-46-02](https://user-images.githubusercontent.com/63583961/126290838-e3c80892-2db4-4cb4-ae69-1f3ead425089.png)

Connection secure and certifica thing
![Screenshot_2021-07-20-11-47-04](https://user-images.githubusercontent.com/63583961/126291043-8282e6c9-8fa3-4f9e-a9e5-6df38a641582.png)

![Screenshot_2021-07-20-11-47-09](https://user-images.githubusercontent.com/63583961/126291101-bb3ef860-a9a5-4ee2-a3bb-61590a38d73a.png)

And last one is that Copy-Paste thing.
![Screenshot_2021-07-20-11-49-13](https://user-images.githubusercontent.com/63583961/126291342-9a83b460-2a53-4363-a7b6-c3f37c5ad7dd.png)

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)

**Comment by kyoyacchi** [comment]
....

**Comment by d3ward** [comment]
> ....

Is that bug from latest build ? Because i checked and doesn't seem to be there anymore the bugs

**Comment by kyoyacchi** [comment]
> > ....
> 
> Is that bug from latest build ? Because i checked and doesn't seem to be there anymore the bugs

Yes, that's right. It was on previous version(s), sorry for bothering.
