### ISSUE TITLE
Sea Sick and Headaches while Scrolling after latest Update

### ISSUE THREAD

**Issue by blitterz** [kiwibrowser/src#403]
![Screenshot_20210725-160723_Kiwi Browser](https://user-images.githubusercontent.com/76099106/126902059-de8832c9-25c1-4a38-b9a7-8bd9b1e0843b.jpg)

please fix asap

**Comment by d3ward** [comment]
Check out latest Kiwi builds on [src.next](https://github.com/kiwibrowser/src.next)
If bug still persist , open a new issue in the .next repo
