### ISSUE TITLE
Updates have moved to src.next repository

### ISSUE THREAD

**Issue by Maxxee** [kiwibrowser/src#405]
So does that mean that the latest Play Store version is actually the code base of Kiwi Next?

In the last few days there have been at least three updates for Kiwi (not Next) Browser in the Play Store. Are these actually Kiwi Next?

PS: Also, as it now replaces Kiwi Browser since a few weeks instead of installing separately, how do I decide which version to install?

**Comment by Maxxee** [comment]
Alright, whose feet I need to kiss to get a reply, preferably from the dev, when a later question was already answered.

**Comment by d3ward** [comment]
Yes . Updates on Play Store are now the Kiwi Next builds .
Github build are like beta for testing purposes , before deploy on Play Store
