### ISSUE TITLE
List of flags to be added in settings 

### ISSUE THREAD

**Issue by d3ward** [kiwibrowser/src#41]
Use this issue to discuss about flags that should be added inside settings. It can let the user to set flags without going into the long list of flags in chrome://flags

There are 4 layout for tabs , they can be grouped into a select :
(checked one are already in settings)
- [x]  Default layout ( when the accesibility one is disabled )

- [x]  #enable-accessibility-tab-switcher 
- [ ]  #enable-tab-grid-layout

- [ ]  #enable-horizontal-tab-switcher

Other flags

- [ ] #enable-search-ready-omnibox

**Comment by hjyoung1** [comment]
Why #enable-tab-grid-layout Is in the list when it's not even available in flags section?

**Comment by d3ward** [comment]
> Why #enable-tab-grid-layout Is in the list when it's not even available in flags section? 

It can be imported, some users suggested grid-layout to be added

**Comment by mehta1190** [comment]
Though there is already a very fine working night/dark mode in kiwi, #enable-force-dark and #darken-websites-checkbox-in-themes-setting flags can also be considered. Also in #enable-force-dark flag instead of "enabled", "enabled with selective inversion of everything" works much better.

**Comment by muznyo** [comment]
I would like google duet flag, tab groups flag, qr code flag and all omnibox flags

**Comment by kakhulu31** [comment]
+1 for tab groups and grid layout

**Comment by atahabaki** [comment]
What flag should be used for extensions which uses omnibox? (e. g. [chrome-smartbox](https://github.com/atahabaki/chrome-smartbox))

**Comment by b1ackfa1c0n** [comment]
Are there any news on this regard ?
