### ISSUE TITLE
New tab page

### ISSUE THREAD

**Issue by bhnettv** [kiwibrowser/src#44]
Hello friend
I have one question about newtab page extension on Kiwi Browser. Why every time newtab page is opened it make connections to sites that is saved? Is it grabbing just icons and if it is , is there posibility to save icons somewhare in folder when we save page. 
Thanks.

**Comment by kiwibrowser** [comment]
The connections are pre-established to speedup the first time to click when you open the browser.

It's done via the preconnect directive in the .html code of the new tab page so if you change the default home page then this is not the case.

We can discuss the feature as well if there is a reason to avoid preconnect that you see (it's preconnect, not preload)
