### ISSUE TITLE
toolbar can't be hidden on tablet 

### ISSUE THREAD

**Issue by cuifua** [kiwibrowser/src#45]

**Comment by SoumyBhow** [comment]
Yeah the UI on a tablet isn't the same as on a phone. Bottom omnibox was missing and the dark mode wouldn't work properly. I had to resort to using an Xposed module (App Settings, but it doesn't work on Android 8+ I think) to increase the DPI of the app to make it think it was on a phone and fix the UI.

**Comment by michallepicki** [comment]
I like the full-featured desktop-like toolbar that shows up in bigger windows (I use kiwi in android desktop mode) and want it to stay this way, so maybe if some people prefer the mobile toolbar this could be an option in settings?

**Comment by SzendroiImre** [comment]
I'd like for the option to be available on tablets too. Kiwi is so close to my ideal browser but this auto-hiding stuff is hurting my eyes.

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
