### ISSUE TITLE
Export currently open tabs

### ISSUE THREAD

**Issue by karanrajpal14** [kiwibrowser/src#46]
Not sure whether this will get implemented but it's definitely nice to have. Is there any chance you could add a feature to export currently open tabs to a text file or something of that sort? I often leave some tabs open that I haven't had the chance to work on yet and just the other day I lost around 50 tabs by mis-clicking and closing them all. It would be great if you would consider adding a native "tab-backup" feature.

**Comment by SuperSandro2000** [comment]
Maybe this extensions is what you are searching for https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko

Not sure if it works in kiwi though

**Comment by d3ward** [comment]
https://github.com/Karna98/Save-Tabs
This one works well , also Kiwi recently got a big update  on [src.next](https://github.com/kiwibrowser/src.next)
