### ISSUE TITLE
Push notifications do not work

### ISSUE THREAD

**Issue by sturmen** [kiwibrowser/src#50]
Kiwi Browser: **77.0.3865.92**
Operating system  
**Android 10.0.0; SM-G988U Build/QP1A.190711.020**

I have tested with multiple sites, but the most straightforward is [bennish.net](https://www.bennish.net/web-notifications.html). No matter what I do, the console always outputs "Permission to display: denied". This holds true for other sites as well.

**Comment by Cyberpunk-77** [comment]
There's a workaround to make notifications partially working.
Open 
`kiwi://settings/content/notifications`
And add site (where you want to enable notifications) in allowed section. 
Now refresh your site and enable notifications.
This will give notifications only when app is running. In foreground or background.

**Comment by Goltergaul** [comment]
Unfortunatel the workaround is not working either for me

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
