### ISSUE TITLE
extensions in homescreen or homepage

### ISSUE THREAD

**Issue by muznyo** [kiwibrowser/src#53]
Add an option to add extension in homescreen or homepage

**Comment by d3ward** [comment]
You can already set a ntp extension as Kiwi homepage
After installing the extension set this as your homepage ( Settings->Home Page )
 `chrome://newtab`

**Comment by muznyo** [comment]
No, i didn't mean ntp extensions, but extensions that have settings tab, so you can access that extension setting in ntp
