### ISSUE TITLE
AMP blocker not working

### ISSUE THREAD

**Issue by ChrisDaDerp** [kiwibrowser/src#54]
Video:
https://photos.app.goo.gl/CaPnwicKr5Kfgjpc8

Samsung Galaxy S8 SM-G950U
Android 9, One UI

**Comment by kiwibrowser** [comment]
(Thanks for the video!)

**Comment by gello0** [comment]
AMP blocker is working fine. But links do appear to have ```amp``` in them have. It has been like this since beginning . 

Try removing ```/amp``` from the links and reload, the website should appear similar.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
