### ISSUE TITLE
Better "Add Page" option

### ISSUE THREAD

**Issue by d3ward** [kiwibrowser/src#57]
Revamp "Add page" option to a menu :

- [ ] Add to bookmarks 

- [x] Add to homescreen

- [ ] Add to NTP

**Comment by kiwibrowser** [comment]
- Add to homescreen can be done by executing (evaluating) javascript using evaluateJavascript on the homepage (see AMP script for example in the java code)
or:
- by spawning an invisible renderer to the homepage and evaluating javascript code inside
or:
- in a much more complicated way (not recommended), by opening localStorage

**Comment by kiwibrowser** [comment]
Something like that:
if (id == R.id.add_to_homepage-id) {
            LoadUrlParams loadUrlParams = new LoadUrlParams("javascript:alert(document.location)");
             currentTab.loadUrl(loadUrlParams);
         }

===

or background renderer (probably better, since you run directly in the right scope):
                 mWebContents = WebContentsFactory.createWebContents(false, true);

                    String toLoad = "<script type='text/javascript'>window.setInterval(function () { console.log('!!!!!!!!!! NEW MESSAGE FROM LOCAL-NTP ' + Math.random()), 1000});</script>";
                    LoadUrlParams loadUrlParams = LoadUrlParams.createLoadDataParamsWithBaseUrl(toLoad, "text/html", false, "chrome://local-ntp/", n
ull);
                     loadUrlParams.setCanLoadLocalResources(true);
                     mWebContents.getNavigationController().loadUrl(loadUrlParams);
