### ISSUE TITLE
List of Extension related improvements

### ISSUE THREAD

**Issue by d3ward** [kiwibrowser/src#62]
- [ ] Enable on Incognito Mode
- [ ] Support for popup.html of extensions ( instead of open extension in a new tab create an wrapped 	 
overlay of extension content)

- [ ] When install extension from zip show a message if there is an error like "manifest file not found"

- [ ] Notify users when extensions have been disabled due to permissions changes

- [ ] Remove extension download notification automatically after installation is complete

**Comment by d3ward** [comment]
#36

**Comment by DragoCubed** [comment]
Instead of a popup on the webpage, I'd prefer a page like the bookmarks or downloads pages. I may have understood that incorrectly though.

**Comment by d3ward** [comment]
> Instead of a popup on the webpage, I'd prefer a page like the bookmarks or downloads pages. I may have understood that incorrectly though.
Basically the popup should be like what you are talking about  but implemented in a different way . Actually the popup of an extension it opens  in a new tab . 
Making it opens in the current page like an **_overlay_** is better and easier task than implement in browser page ( like bookmarks page or download ) . But the popup in overlay can act like bookmark page by taking all the space available  so the result should be the same

**Comment by SoumyBhow** [comment]
> > Instead of a popup on the webpage, I'd prefer a page like the bookmarks or downloads pages. I may have understood that incorrectly though.
> 
> Basically the popup should be like what you are talking about  but implemented in a different way . Actually the popup of an extension it opens  in a new tab . 
> Making it opens in the current page like an **_overlay_** is better and easier task than implement in browser page ( like bookmarks page or download ) . But the popup in overlay can act like bookmark page by taking all the space available  so the result should be the same
> 

Will it be possible for Kiwi to not open extensions in a new tab and do something like what Yandex does with the extension UI over the site? I do find the overlay way (I don't know the right term) cleaner and less confusing and bothersome.
