### ISSUE TITLE
Tabs queue

### ISSUE THREAD

**Issue by d3ward** [kiwibrowser/src#67]
(from reddit) 
Add a feature like of Mozilla Firefox where if we want to read a link or page, we add it to tab queue.
It's useful for someone who cannot read at that point of time and will later like I do with Firefox. Very productive and useful

**Comment by Cyberpunk-77** [comment]
Isn't extensions already available to achieve this?
Tab manager extensions.

**Comment by d3ward** [comment]
> Aren't extensions already available to achieve this?
> Tab manager extensions. 

I don't think so because some tabs api are missing. If you find an extension that can achieve this, link it so can be done some test

**Comment by d3ward** [comment]
This feature can be achieved with extensions
