### ISSUE TITLE
Chrome Dev Tools

### ISSUE THREAD

**Issue by laem** [kiwibrowser/src#7]
Would it be possible to include the dev tools in the build, like it is on all the desktop browsers ? 

If it's a size problem, would it be feasable to include them as an extension, using this package ? https://github.com/ChromeDevTools/devtools-frontend

Android is more and more usable as a desktop OS plugged on a bigger screen (see Samsung Dex;Huawei "easy projection", now wireless; native Android support in 10 : bad UI but a base for development)

**Comment by kiwibrowser** [comment]
It's a good idea. Technically possible too (devtools is built as part of the extensions system).

**Comment by michallepicki** [comment]
I'd like to have the DevTools available without any UI changes. I would use it in Android Desktop mode (Samsung DeX in my case) so the regular DevTools UI will be perfectly usable with mouse and keyboard.

This may be a MVP solution to this issue, just adding DevTools with the desktop UI as is, and touch-friendly UI could be added later. Still, I'd like to have an option to use the regular desktop DevTools UI.

**Comment by laem** [comment]
For a touch version of devtools, checkout Eruda. I agree, what we need first is the regular devtools desktop UI :)

**Comment by kiwibrowser** [comment]
https://play.google.com/store/apps/details?id=io.alcatraz.f12

This may be a possible solution to rooted users in the meantime.

I have reached out to the developer to offer him to buy the app so we could offer it as a Kiwi Browser companion (without root)

**Comment by laem** [comment]
Nice ! You need to sign F12 + Kiwi with the same id to communicate between both apps right ?

**Comment by laem** [comment]
Wait, it's here no ? https://github.com/Alcatraz323/F12_New

**Comment by kiwibrowser** [comment]
mhhh, great find !, yes and it's GPL, so doable as a standalone companion (let's say "Kiwi Browser - Devtools" or something like that

We need to see how to connect to Kiwi via a trusted communication protocol.
Otherwise, we can do the integrated devtools, but the idea of external app is interesting too

**Comment by FluorescentHallucinogen** [comment]
Any progress?

Recently, I've opened https://crbug.com/1141112, but it has been closed as Won't Fix (I'm not surprised).

**Comment by laem** [comment]
I believe those feature requests (I did the same a few years ago for Firefox) are closed because the teams think porting devtools to mobile devices would suppose making a touch UI. That's not the case, we just need the *exact same devtools* on a big Android screen (tablet or desktop android).

**Comment by Oranko** [comment]
Added in the latest version
