### ISSUE TITLE
Kiwi browser keeps crashing. 

### ISSUE THREAD

**Issue by dkATneg** [kiwibrowser/src#72]
Whenever I try to add chrome extension it keeps crashing for me.. I've tried reinstalling but it didn't work.. I recently did factory reset on my phone after that I'm facing this issue. In currently on android 10 and using op 7 pro. Tried to look for the solution or the same issue but apparently I'm the only one facing this issue... Any help is appreciated, thnx..

**Comment by Cyberpunk-77** [comment]
Happens when installing any extensions? Or only some specific extensions crash browser?

**Comment by dkATneg** [comment]
@Cyberpunk-77 for every every extension.. Tried dark reader, ublock etc

**Comment by Oranko** [comment]
Update to the latest version
