### ISSUE TITLE
Pls help.. Kiwi browser keeps crashing. 

### ISSUE THREAD

**Issue by dkATneg** [kiwibrowser/src#77]
Kiwi browser keeps crashing for me.. Whenever I try to install any extension on it.. Tried reinstalling and giving all the permission but still don't know why it's not working... When I press add to chrome it starts downloading and then suddenly goes to app info page..

**Comment by hjyoung1** [comment]
You already have https://github.com/kiwibrowser/src/issues/72 open for same problem.
Please don't open duplicate issues.

**Comment by dkATneg** [comment]
@hjyoung1 OK but i didn't find any solution so i reopened it...

**Comment by DJCrashdummy** [comment]
@dkATneg your original issue #72 was never closed... so there is nothing to reopen.

**Comment by dkATneg** [comment]
Have already opened similar issue!
