### ISSUE TITLE
Website saying my browser is out of date

### ISSUE THREAD

**Issue by kaecy** [kiwibrowser/src#78]
I have version 77. That is all I can say.

![Screenshot_20200504_014232](https://user-images.githubusercontent.com/4354982/80930056-9f02bb80-8da8-11ea-8b4b-60c2400f17a7.jpg)

**Comment by blubbll** [comment]
Get a extension to change your useragent to a more recent one ᕕ( ᐛ )ᕗ

**Comment by kaecy** [comment]
I have to use an extension from now on? What is the latest user agent?
What is the recommended extension? I don't use extensions but I'll try this.

**Comment by blubbll** [comment]
The most important part is the version number itself. I would recommend opening a mobile browser where the page works and using that ua string. You can get it via https://www.whatismybrowser.com/detect/what-is-my-user-agent for example. I think it will take some more time before we can see new kiwi releases, so this may be the way to go. Good luck!

**Comment by kaecy** [comment]
Even github have stopped supporting it.

![Screenshot_20200805_203713](https://user-images.githubusercontent.com/4354982/89456242-78fc0700-d75b-11ea-8a26-e2e58d3b0716.jpg)

**Comment by SuperSandro2000** [comment]
> less bugs because less updated

thats not true. It has all the bugs Chromium fixed upstream that where included in this version.

**Comment by Dev-i-l** [comment]
fixed in latest version @kaecy , you can close this now

**Comment by kaecy** [comment]
I have version Git201030 (weird scheme). No works stills.
![Screenshot_20201103_120710](https://user-images.githubusercontent.com/4354982/97983486-48b11c80-1dcd-11eb-8c5e-110d9df52d7e.jpg)

**Comment by Oranko** [comment]
The rebased to the latest chromium should have fixed it. Please update
