### ISSUE TITLE
Icons are difficult to see in the main menu in night mode

### ISSUE THREAD

**Issue by kiwibrowser** [kiwibrowser/src#79]
Received by e-mail (and agreeing with it):
Using Diamond Black theme and Night mode, the five symbols across the top of the menu (including bookmark) are very difficult to see because the implementation of dark gray on black background is very hard to distinguish.

The solution is as simple as changing the symbol/text colour from dark gray to white while keeping the existing black background. For me, I always struggle to see the bookmark icon even with my device brightness at maximum.

**Comment by kiwibrowser** [comment]
![gg1](https://user-images.githubusercontent.com/40272275/80894341-e292f200-8ce2-11ea-92ff-14a3471f2551.jpg)

**Comment by M-A-R-T-I-N-1** [comment]
May the text in the menu respect the contrast setting?

**Comment by M-A-R-T-I-N-1** [comment]
Also the blinking cursor in text boxes is difficult to see as it doesn't respect the contrast setting.

**Comment by M-A-R-T-I-N-1** [comment]
The arrow (hope the icon on the very left is arrow, as I can't see it) icon on the top bar when editing bookmarks is invisible for me, the trashcan icon is visible, but poorly.

**Comment by M-A-R-T-I-N-1** [comment]
The new tab plus becomes very dark after you open anonymous tab, go to the tab switcher, and close the anonymous tab.
