### ISSUE TITLE
Search Engines not added

### ISSUE THREAD

**Issue by realpanzer** [kiwibrowser/src#83]
I have tried to add some search engines by visiting their pages + search. I have managed to add:
https://swisscows.ch
https://gomu.ca
https://www.runnaroo.com

I couldn't add the folowing ones:
https://private.sh
https://www.onesearch.com
https://search.joshwho.net (Kiwi can't load the page properly)

Could you add at least those with end-to-end encryption manually somehow?

**Comment by M-A-R-T-I-N-1** [comment]
Tried to add https://searx.run with no success.

**Comment by jvandenbroek** [comment]
Maybe an option to add custom search engine would be feasible instead? So i can add my own Searx instance manually.

**Comment by dagaz** [comment]
I have the same problem with NAS hosted searx instance (on 192.168.0.x).
I would also appreciate an option to ad a custom search engine.

**Comment by netroby** [comment]
Wish options add custom search engine;

**Comment by d3ward** [comment]
Check out latest Kiwi builds
If bug still persist , open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
