### ISSUE TITLE
extension api missing 

### ISSUE THREAD

**Issue by ale82to** [kiwibrowser/src#85]
please fix this 2 extensions which work perfectly in yandex :+1:
Shortkeys (Custom Keyboard Shortcuts):
https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck

and

Alt-Q-Switch-Tabs-Keyboard-Shortcut

https://chrome.google.com/webstore/detail/alt-%2B-q-switch-tabs-keybo/odhjcgnlbagjllfbilicalpigimhdcll

**Comment by rururux** [comment]
duplicate #43
