### ISSUE TITLE
Need a Grammar check in README.md file

### ISSUE THREAD

**Issue by Deeksha2501** [kiwibrowser/src#89]
There are some grammar issues in README.md file.
Can I work on this issue?

**Comment by kiwibrowser** [comment]
Yes, just fork the project, make edits and open a merge request

Thank you for your time!

**Comment by Deeksha2501** [comment]
Thank you, I will do it today!

**Comment by TheEvilSkeleton** [comment]
@Deeksha2501 I'm a contributor of the README, and I would want to thank you for fixing some of my typos :)

**Comment by Deeksha2501** [comment]
THANK YOU SO MUCH :)
I JUST TRIED TO MAKE IT BETTER
